<a href="https://colab.research.google.com/github/SandroBiten/PUC_BIGDATA/blob/main/Machine_Learning__Coleta_de_Dados_Pos_BIGDATA_20220530.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><h1><b><i>MACHINE LEARNING WITH PYTHON</i></b></h1></center>

#**Importar libraries**

In [ ]:
import numpy as np
import pandas as pd
import glob

np.set_printoptions(formatter = {'float': lambda x: "{0:0.2f}".format(x)})

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#**Montar Drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#**Dados IBGE**

##**Captura IBGE - Pesquisa Nacional de Saneamento Básico - 2017**

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/SANEAMENTO 2017/'

Saneamento_10 = pd.read_csv(folder_path + "Pesquisa Nacional de Saneamento Básico (2017)-AC.csv", sep=',', encoding="UTF-8")
Saneamento_10 = Saneamento_10.iloc[0:0,:].copy() 

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    Saneamento_05 = pd.read_csv(nome_do_arquivo, sep=',', encoding="UTF-8")
    Saneamento_05 ['UF']=str(nome_do_arquivo[-6:-4])
    Saneamento_10 = pd.concat([Saneamento_10, Saneamento_05], axis=0, sort=False)

query = ['1.1.1', '1.2.1']

Saneamento_20 = Saneamento_10[Saneamento_10['Posição'].isin(query)]

colunas = ['Nome', 'Localidade', 'UF', '2017']
Saneamento_20 = Saneamento_20 [colunas].copy()

Saneamento_2017 = Saneamento_20.pivot_table(index=['Localidade', 'UF'], columns= "Nome", values= '2017', aggfunc='sum')

Saneamento_2017 = Saneamento_2017.reset_index()

Saneamento_2017.columns = ['Localidade', 'UF', 'Saneamento_Edificios_Abastecidos_Agua_2017', 'Saneamento_Edificios_Esgotados_2017']

Saneamento_2017 ['Saneamento_Edificios_Abastecidos_Agua_2017'] = Saneamento_2017 ['Saneamento_Edificios_Abastecidos_Agua_2017'].replace('-', 0).copy()
Saneamento_2017 ['Saneamento_Edificios_Esgotados_2017'] = Saneamento_2017 ['Saneamento_Edificios_Esgotados_2017'].replace('-', 0).copy()
Saneamento_2017 ['Saneamento_Edificios_Abastecidos_Agua_2017'] = Saneamento_2017 ['Saneamento_Edificios_Abastecidos_Agua_2017'].fillna(0).copy()
Saneamento_2017 ['Saneamento_Edificios_Esgotados_2017'] = Saneamento_2017 ['Saneamento_Edificios_Esgotados_2017'].fillna(0).copy()
Saneamento_2017 ['Saneamento_Edificios_Abastecidos_Agua_2017'] = Saneamento_2017 ['Saneamento_Edificios_Abastecidos_Agua_2017'].astype('float64')
Saneamento_2017 ['Saneamento_Edificios_Esgotados_2017'] = Saneamento_2017 ['Saneamento_Edificios_Esgotados_2017'].astype('float64')

Saneamento_2017.head()

,Localidade,UF,Saneamento_Edificios_Abastecidos_Agua_2017,Saneamento_Edificios_Esgotados_2017
0,Abadia de Goiás,GO,3015.0,1134.0
1,Abadia dos Dourados,MG,2255.0,2168.0
2,Abadiânia,GO,0.0,0.0
3,Abaetetuba,PA,5277.0,0.0
4,Abaeté,MG,9689.0,163.0

##**Captura IBGE - Pobreza**

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/POBREZA/'

Pobreza_10 = pd.read_csv(folder_path + "Mapa de pobreza e desigualdade-AC.csv", sep=',', encoding="UTF-8")
Pobreza_10 = Pobreza_10.iloc[0:0,:].copy() 

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    Pobreza_05 = pd.read_csv(nome_do_arquivo, sep=',', encoding="UTF-8")
    Pobreza_05 ['UF']=str(nome_do_arquivo[-6:-4])
    Pobreza_10 = pd.concat([Pobreza_10, Pobreza_05], axis=0, sort=False)

query = ['1', '3']

Pobreza_20 = Pobreza_10[Pobreza_10['Posição'].isin(query)]

colunas = ['Nome', 'Localidade', 'UF', '2003']
Pobreza_20 = Pobreza_20 [colunas].copy()

Pobreza_2003 = Pobreza_20.pivot_table(index=['Localidade', 'UF'], columns= "Nome", values= '2003', aggfunc='sum')

Pobreza_2003 = Pobreza_2003.reset_index()

Pobreza_2003.columns = ['Localidade', 'UF', 'Pobreza_%_2003', 'Gini_2003']

Pobreza_2003.head()

            Localidade  UF  Pobreza_%_2003  Gini_2003
0      Abadia de Goiás  GO           37.83       0.40
1  Abadia dos Dourados  MG           34.50       0.41
2            Abadiânia  GO           38.85       0.42
3           Abaetetuba  PA           51.34       0.40
4               Abaeté  MG           36.17       0.42

##**Captura IBGE - PIB**

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/PIB/'

PIB_10 = pd.read_csv(folder_path + "Produto Interno Bruto dos Municípios-AC.csv", sep=',', encoding="UTF-8")
PIB_10 = PIB_10.iloc[0:0,:].copy() 

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    PIB_05 = pd.read_csv(nome_do_arquivo, sep=',', encoding="UTF-8")
    PIB_05 ['UF']=str(nome_do_arquivo[-6:-4])
    PIB_10 = pd.concat([PIB_10, PIB_05], axis=0, sort=False)

PIB_10["Posição_2"] = PIB_10["Posição"]
    
dic = {"1.1": 'PIB a preços correntes', '2.1': 'PIB per capita', "3.1": 'Valor adicionado bruto a preços correntes'}

dic = {r"\b{}\b".format(k): v for k, v in dic.items()}

PIB_10["Posição_2"] = PIB_10["Posição_2"].replace(dic, regex=True)

query = ['2.1']

PIB_20 = PIB_10[PIB_10['Posição'].isin(query)]

colunas = ['Posição_2', 'Localidade', 'UF', '2019']

PIB_20 = PIB_20 [colunas].copy()

PIB_2019 = PIB_20.pivot_table(index=['Localidade', 'UF'], columns= "Posição_2", values= '2019', aggfunc='sum')

PIB_2019 = PIB_2019.reset_index()

PIB_2019.columns = ['Localidade', 'UF', 'PIB_per_capita_2019']

PIB_2019.head()

            Localidade  UF  PIB_per_capita_2019
0      Abadia de Goiás  GO             23061.21
1  Abadia dos Dourados  MG             18254.66
2            Abadiânia  GO             17302.04
3           Abaetetuba  PA              9480.05
4               Abaeté  MG             22262.55

##**Captura IBGE - Panorama municipal**

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/Panorama municipal/'

Panorama_10 = pd.read_csv(folder_path + "Panorama municipal-AC.csv", sep=',', encoding="UTF-8")
Panorama_10 = Panorama_10.iloc[0:0,:].copy() 

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    Panorama_05 = pd.read_csv(nome_do_arquivo, sep=',', encoding="UTF-8")
    Panorama_05 ['UF']=str(nome_do_arquivo[-6:-4])
    Panorama_10 = pd.concat([Panorama_10, Panorama_05], axis=0, sort=False)

query = ['1.2', '1.3', '3.1.1', '3.1.2', '4.1', '4.2.1', '5.1', '5.2.1.1.1', '5.3']

Panorama_20 = Panorama_10[Panorama_10['Posição'].isin(query)]

dic = {"3.1.2": "Anos_finais_do_ensino_fundamental_2015", "1.2": "Esgotamento_sanitário_adequado_%_2010", 
       "1.3": "Urbanização_de_vias_públicas_%_2010", "3.1.1": "Anos_iniciais_do_ensino_fundamental_2015",
       "4.1": "Internações_por_diarreia_2016", "4.2.1": "Mortalidade_infantil_2012_2014",
       "5.1": "População_ocupada_2019", "5.2.1.1.1": "Classe_de_rendimento_nominal_mensal_domiciliar_per_capita_Até_meio_salário_mínimo_%_2010",
       "5.3": "Salário_médio_mensal_2015"}

dic = {r"\b{}\b".format(k): v for k, v in dic.items()}

Panorama_20["Posição"] = Panorama_20["Posição"].replace(dic, regex=True)

colunas = ['Posição', 'Localidade', 'UF', '2010', '2012-2014', '2014', '2015', '2016', '2017', '2018', '2019']

Panorama_20 = Panorama_20 [colunas].copy()

Panorama_20 = Panorama_20.fillna(0).copy()

Panorama_20 ['2018'] = Panorama_20 ['2018'].astype('float64')

for column in Panorama_20:
    if Panorama_20[column].sum() == 0:
        Panorama_20.drop([column], axis=1, inplace=True)

Panorama_Municipal_2010_2019 = Panorama_20.pivot_table(index=['Localidade', 'UF'], columns= "Posição", values= ['2010', '2012-2014', '2014', '2015', '2016', '2017', '2018', '2019'], aggfunc='sum')

Panorama_Municipal_2010_2019 = Panorama_Municipal_2010_2019.reset_index()

for column in Panorama_Municipal_2010_2019:
    if Panorama_Municipal_2010_2019[column].sum() == 0:
        Panorama_Municipal_2010_2019.drop([column], axis=1, inplace=True)

Panorama_Municipal_2010_2019.drop([('2015', 'População_ocupada_2019'), ('2014', 'Salário_médio_mensal_2015'), ('2014', 'População_ocupada_2019'), ('2016', 'População_ocupada_2019'), ('2017', 'População_ocupada_2019'), ('2018', 'População_ocupada_2019')], axis=1, inplace=True)

Panorama_Municipal_2010_2019.columns = Panorama_Municipal_2010_2019.columns.droplevel(0)

Panorama_Municipal_2010_2019.columns = ['Localidade', 'UF', 'Rendimento_mensal_per_capita_Até_meio_SM_%_2010',
       'Saneamento_Esgotamento_adequado_%_2010',
       'Urbanização_%_vias_públicas_2010', 'Mortalidade_infantil_PER_MIL_2012_2014',
       'Educacao_Anos_finais_Fundamental_2015',
       'Educacao_Anos_iniciais_Fundamental_2015', 'Rendimento_médio_mensal_SM_2015',
       'Internações_Diarreia_PER_MIL_2016', 'População_ocupada_%_2019']

Panorama_Municipal_2010_2019 = Panorama_Municipal_2010_2019.fillna(0).copy()

Panorama_Municipal_2010_2019.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Localidade,UF,Rendimento_mensal_per_capita_Até_meio_SM_%_2010,Saneamento_Esgotamento_adequado_%_2010,Urbanização_%_vias_públicas_2010,Mortalidade_infantil_PER_MIL_2012_2014,Educacao_Anos_finais_Fundamental_2015,Educacao_Anos_iniciais_Fundamental_2015,Rendimento_médio_mensal_SM_2015,Internações_Diarreia_PER_MIL_2016,População_ocupada_%_2019
0,Abadia de Goiás,GO,30.6,35.0,0.0,18.6,4.4,5.5,2.1,0.5,22.6
1,Abadia dos Dourados,MG,35.0,59.9,36.3,15.3,5.0,6.8,1.7,1.7,26.0
2,Abadiânia,GO,35.9,77.5,0.9,17.4,4.9,5.1,1.8,0.1,11.7
3,Abaetetuba,PA,52.6,16.5,5.1,14.0,3.4,4.4,1.8,4.2,7.5
4,Abaeté,MG,33.4,85.0,13.9,13.1,4.3,6.9,1.7,0.8,19.8

##**Captura IBGE - Censo Educação**

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/Censo EDUCACAO/'

Educacao_10 = pd.read_csv(folder_path + "Censo-AC.csv", sep=',', encoding="UTF-8")
Educacao_10 = Educacao_10.iloc[0:0,:].copy() 

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    Educacao_05 = pd.read_csv(nome_do_arquivo, sep=',', encoding="UTF-8")
    Educacao_05 ['UF']=str(nome_do_arquivo[-6:-4])
    Educacao_10 = pd.concat([Educacao_10, Educacao_05], axis=0, sort=False)

query = ['6.1', '6.1.2.1', '6.1.2.2', '6.1.2.3', '6.1.2.4', '6.1.4.1', '6.1.4.2']

Educacao_20 = Educacao_10[Educacao_10['Posição'].isin(query)]

dic = {'6.1': 'Amostra_Educação_Pessoas_10_anos_ou_mais_2010', 
       '6.1.2.1': 'Amostra_Educação_Pessoas_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_2010', 
       '6.1.2.2': 'Amostra_Educação_Pessoas_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_2010', 
       '6.1.2.3': 'Amostra_Educação_Pessoas_10_anos_ou_mais_Médio_completo_e_superior_incompleto_2010', 
       '6.1.2.4': 'Amostra_Educação_Pessoas_10_anos_ou_mais_Superior_completo_2010', 
       '6.1.4.1': 'Amostra_Educação_Pessoas_10_anos_ou_mais_Ocupada_2010', 
       '6.1.4.2': 'Amostra_Educação_Pessoas_10_anos_ou_mais_Não ocupada_2010'}

dic = {r"\b{}\b".format(k): v for k, v in dic.items()}

Educacao_20["Posição"] = Educacao_20["Posição"].replace(dic, regex=True)

colunas = ['Posição', 'Localidade', 'UF', '2010']

Educacao_20 = Educacao_20 [colunas].copy()

Educacao_20 = Educacao_20.fillna(0).copy()

Educacao_30 = Educacao_20.pivot_table(index=['Localidade', 'UF'], columns= "Posição", values= ['2010'], aggfunc='sum')

Educacao_30 = Educacao_30.reset_index()
Educacao_30.columns = Educacao_30.columns.droplevel(0)

colunas = ['Localidade', 'UF', 'Educação_Amostra_10_anos_ou_mais_2010', 
           'Educação_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_%_2010',
           'Educação_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_%_2010',
           'Educação_10_anos_ou_mais_Médio_completo_e_superior_incompleto_%_2010',
           'Educação_10_anos_ou_mais_Superior_%_completo_2010', 
           'Educação_10_anos_ou_mais_Ocupada_%_2010', 'Educação_10_anos_ou_mais_Não_ocupada_%_2010']

Educacao_30.columns = colunas

Educacao_30['Educação_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_%_2010'] = Educacao_30['Educação_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_%_2010'] / Educacao_30['Educação_Amostra_10_anos_ou_mais_2010'] * 100
Educacao_30['Educação_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_%_2010'] = Educacao_30['Educação_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_%_2010'] / Educacao_30['Educação_Amostra_10_anos_ou_mais_2010'] * 100
Educacao_30['Educação_10_anos_ou_mais_Médio_completo_e_superior_incompleto_%_2010'] = Educacao_30['Educação_10_anos_ou_mais_Médio_completo_e_superior_incompleto_%_2010'] / Educacao_30['Educação_Amostra_10_anos_ou_mais_2010'] * 100
Educacao_30['Educação_10_anos_ou_mais_Superior_%_completo_2010'] = Educacao_30['Educação_10_anos_ou_mais_Superior_%_completo_2010'] / Educacao_30['Educação_Amostra_10_anos_ou_mais_2010'] * 100
Educacao_30['Educação_10_anos_ou_mais_Ocupada_%_2010'] = Educacao_30['Educação_10_anos_ou_mais_Ocupada_%_2010'] / Educacao_30['Educação_Amostra_10_anos_ou_mais_2010'] * 100
Educacao_30['Educação_10_anos_ou_mais_Não_ocupada_%_2010'] = Educacao_30['Educação_10_anos_ou_mais_Não_ocupada_%_2010'] / Educacao_30['Educação_Amostra_10_anos_ou_mais_2010'] * 100

Educacao_30.drop(['Educação_Amostra_10_anos_ou_mais_2010'], axis=1, inplace=True)

Educacao_30.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Localidade,UF,Educação_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_%_2010,Educação_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_%_2010,Educação_10_anos_ou_mais_Médio_completo_e_superior_incompleto_%_2010,Educação_10_anos_ou_mais_Superior_%_completo_2010,Educação_10_anos_ou_mais_Ocupada_%_2010,Educação_10_anos_ou_mais_Não_ocupada_%_2010
0,Abadia de Goiás,GO,55.710594,19.621016,19.000861,5.650301,60.172265,39.827735
1,Abadia dos Dourados,MG,62.810058,20.013592,12.062521,4.858987,56.371050,43.611961
2,Abadiânia,GO,59.061597,17.307835,19.464828,3.513453,54.725372,45.274628
3,Abaetetuba,PA,62.683030,15.593946,18.229222,2.926718,46.680888,53.319112
4,Abaeté,MG,66.133831,14.386566,13.917604,5.118249,54.903938,45.096062

##**Captura IBGE - IDH**

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/IDH/'

IDH_10 = pd.read_csv(folder_path + "Índice de Desenvolvimento Humano-AC.csv", sep=',', encoding="UTF-8")
IDH_10 = IDH_10.iloc[0:0,:].copy() 

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    IDH_05 = pd.read_csv(nome_do_arquivo, sep=',', encoding="UTF-8")
    IDH_05 ['UF']=str(nome_do_arquivo[-6:-4])
    IDH_10 = pd.concat([IDH_10, IDH_05], axis=0, sort=False)

query = ['1']

IDH_2010 = IDH_10[IDH_10['Posição'].isin(query)]

colunas = ['Localidade', 'UF', '2010']

IDH_2010 = IDH_2010 [colunas].copy()

IDH_2010.columns = ['Localidade', 'UF', 'IDH_2010']

IDH_2010 ['IDH_2010'] = IDH_2010 ['IDH_2010'].replace('-', 0).copy()
IDH_2010 ['IDH_2010'] = IDH_2010 ['IDH_2010'].fillna(0).copy()
IDH_2010 ['IDH_2010'] = IDH_2010 ['IDH_2010'].astype('float64')

IDH_2010.head()

                Localidade  UF  IDH_2010
0  Amparo do São Francisco  SE     0.611
1                 Aquidabã  SE     0.578
2                  Aracaju  SE     0.770
3                    Arauá  SE     0.595
4             Areia Branca  SE     0.579

##**Captura IBGE - Finanças Públicas**

In [ ]:
folder_path_DF = '/content/drive/MyDrive/Pos/Finanças Públicas DF/'

Financas_10_DF = pd.read_csv(folder_path_DF + "Finanças públicas-x-DF.csv", sep=';', encoding="UTF-8")

query = ['1.1']

Financas_10_DF = Financas_10_DF[Financas_10_DF['Nível'].isin(query)]

Financas_10_DF ['Localidade'] = 'Brasília'
Financas_10_DF ['UF'] = 'DF'

colunas = ['Localidade', 'UF', '2017']

Financas_10_DF = Financas_10_DF [colunas].copy()

Financas_10_DF.columns = ['Localidade', 'UF', 'Despesas_orçamentárias_empenhadas_2017']

Financas_10_DF

###############################################################################################################################

folder_path = '/content/drive/MyDrive/Pos/Finanças Públicas/'

Financas_10 = pd.read_csv(folder_path + "Finanças públicas-AC.csv", sep=',', encoding="UTF-8")
Financas_10 = Financas_10.iloc[0:0,:].copy() 

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    Financas_05 = pd.read_csv(nome_do_arquivo, sep=',', encoding="UTF-8")
    Financas_05 ['UF']=str(nome_do_arquivo[-6:-4])
    Financas_10 = pd.concat([Financas_10, Financas_05], axis=0, sort=False)

query = ['1.1']

Financas_20 = Financas_10[Financas_10['Posição'].isin(query)]

Financas_20['2017'] = Financas_20['2017'] * Financas_20['Multiplicador']

colunas = ['Localidade', 'UF', '2017']

Financas_2017 = Financas_20 [colunas].copy()

Financas_2017.columns = ['Localidade', 'UF', 'Despesas_orçamentárias_empenhadas_2017']

Financas_2017 = pd.concat([Financas_2017, Financas_10_DF], axis=0, sort=False)

Financas_2017 = Financas_2017.fillna(0).copy()

Financas_2017.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

             Localidade  UF  Despesas_orçamentárias_empenhadas_2017
1        Águas Formosas  MG                             40811211.89
2       Oliveira Fortes  MG                             10375164.44
3           Barra Longa  MG                             16229084.73
4  Diogo de Vasconcelos  MG                             12099255.41
5            Bertópolis  MG                             14494197.07

##**Captura IBGE - Educação**

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/EDUCACAO/'

Educacao_50 = pd.read_csv(folder_path + "Índice de Desenvolvimento da Educação Básica-AC.csv", sep=',', encoding="UTF-8")
Educacao_50 = Educacao_50.iloc[0:0,:].copy() 

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    Educacao_45 = pd.read_csv(nome_do_arquivo, sep=',', encoding="UTF-8")
    Educacao_45 ['UF']=str(nome_do_arquivo[-6:-4])
    Educacao_50 = pd.concat([Educacao_50, Educacao_45], axis=0, sort=False)

query = ['1.1.1.1', '1.1.2.1', '1.2.1']

Educacao_60 = Educacao_50[Educacao_50['Posição'].isin(query)]

dic = {"1.1.1.1": 'Ensino_fundamental_Anos_iniciais_Pública', 
       "1.1.2.1": 'Ensino_fundamental_Anos_finais_Pública', 
       "1.2.1": "Ensino médio_Pública"}

dic = {r"\b{}\b".format(k): v for k, v in dic.items()}

Educacao_60["Posição"] = Educacao_60["Posição"].replace(dic, regex=True)

colunas = ['Posição', 'Localidade', 'UF', '2019']

Educacao_60 = Educacao_60 [colunas].copy()

Educacao_2019 = Educacao_60.pivot_table(index=['Localidade', 'UF'], columns= "Posição", values= ['2019'], aggfunc='sum')

Educacao_2019 = Educacao_2019.reset_index()

Educacao_2019.columns = ['Localidade', 'UF', 'Indice_Educacao_Médio_Pública_2019', 
                         'Indice_Educacao_Fundamental_Anos_finais_Pública_2019', 
                         'Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019']

Educacao_2019 ['Indice_Educacao_Médio_Pública_2019'] = Educacao_2019 ['Indice_Educacao_Médio_Pública_2019'].replace('-', 0).copy()
Educacao_2019 ['Indice_Educacao_Fundamental_Anos_finais_Pública_2019'] = Educacao_2019 ['Indice_Educacao_Fundamental_Anos_finais_Pública_2019'].replace('-', 0).copy()
Educacao_2019 ['Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019'] = Educacao_2019 ['Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019'].replace('-', 0).copy()

Educacao_2019 ['Indice_Educacao_Médio_Pública_2019'] = Educacao_2019 ['Indice_Educacao_Médio_Pública_2019'].fillna(0).copy()
Educacao_2019 ['Indice_Educacao_Fundamental_Anos_finais_Pública_2019'] = Educacao_2019 ['Indice_Educacao_Fundamental_Anos_finais_Pública_2019'].fillna(0).copy()
Educacao_2019 ['Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019'] = Educacao_2019 ['Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019'].fillna(0).copy()

Educacao_2019 ['Indice_Educacao_Médio_Pública_2019'] = Educacao_2019 ['Indice_Educacao_Médio_Pública_2019'].astype('float64')
Educacao_2019 ['Indice_Educacao_Fundamental_Anos_finais_Pública_2019'] = Educacao_2019 ['Indice_Educacao_Fundamental_Anos_finais_Pública_2019'].astype('float64')
Educacao_2019 ['Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019'] = Educacao_2019 ['Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019'].astype('float64')

Educacao_2019 ['UF'] = Educacao_2019 ['UF'].replace('R2', 'RR').copy()

Educacao_2019.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Localidade,UF,Indice_Educacao_Médio_Pública_2019,Indice_Educacao_Fundamental_Anos_finais_Pública_2019,Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019
0,Abadia de Goiás,GO,4.6,4.8,5.9
1,Abadia dos Dourados,MG,0.0,5.6,7.3
2,Abadiânia,GO,0.0,4.9,5.8
3,Abaetetuba,PA,3.6,3.6,4.7
4,Abaeté,MG,3.9,4.9,6.9

##**Captura IBGE - Dengue**

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/DENGUE/'

Dengue_10 = pd.read_csv(folder_path + "Notificações de dengue registradas-AC.csv", sep=',', encoding="UTF-8")
Dengue_10 = Dengue_10.iloc[0:0,:].copy() 

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    Dengue_05 = pd.read_csv(nome_do_arquivo, sep=',', encoding="UTF-8")
    Dengue_05 ['UF']=str(nome_do_arquivo[-6:-4])
    Dengue_10 = pd.concat([Dengue_10, Dengue_05], axis=0, sort=False)

query = ['1']

Dengue_2012 = Dengue_10[Dengue_10['Posição'].isin(query)]

colunas = ['Localidade', 'UF', '2012']
Dengue_2012 = Dengue_2012 [colunas].copy()

Dengue_2012.columns = ['Localidade', 'UF', 'Notificações_Dengue_2012']

Dengue_2012 = Dengue_2012.fillna(0).copy()

Dengue_2012.head()

            Localidade  UF  Notificações_Dengue_2012
0             Aquidabã  SE                      18.0
1              Aracaju  SE                    2360.0
2                Arauá  SE                      26.0
3         Areia Branca  SE                       4.0
4  Barra dos Coqueiros  SE                     154.0

##**Captura IBGE - Censo População**

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/Censo POPULACAO/'

Idade_10 = pd.read_csv(folder_path + "Censo-AC.csv", sep=',', encoding="UTF-8")
Idade_10 = Idade_10.iloc[0:0,:].copy() 

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    Idade_05 = pd.read_csv(nome_do_arquivo, sep=',', encoding="UTF-8")
    Idade_05 ['UF']=str(nome_do_arquivo[-6:-4])
    Idade_10 = pd.concat([Idade_10, Idade_05], axis=0, sort=False)

query = ['3.3.1.1', '3.3.1.2', '3.3.1.3', '3.3.1.4', '3.3.1.5', '3.3.1.6', '3.3.1.7', 
         '3.3.1.8', '3.3.1.9', '3.3.1.10', '3.3.1.11']

Idade_20 = Idade_10[Idade_10['Posição'].isin(query)]

dic = {'3.3.1.1': 'Grupo_de_idade_2010_0_a_4_anos', '3.3.1.2': 'Grupo_de_idade_2010_5_a_9_anos', 
       '3.3.1.3': 'Grupo_de_idade_2010_10_a_14_anos', '3.3.1.4': 'Grupo_de_idade_2010_15_a_19_anos', 
       '3.3.1.5': 'Grupo_de_idade_2010_20_a_24_anos', '3.3.1.6': 'Grupo_de_idade_2010_25_a_29_anos', 
       '3.3.1.7': 'Grupo_de_idade_2010_30_a_39_anos', '3.3.1.8': 'Grupo_de_idade_2010_40_a_49_anos', 
       '3.3.1.9': 'Grupo_de_idade_2010_50_a_59_anos', '3.3.1.10': 'Grupo_de_idade_2010_60_a_69_anos', 
       '3.3.1.11': 'Grupo_de_idade_2010_70_a_mais_anos'}

dic = {r"\b{}\b".format(k): v for k, v in dic.items()}

Idade_20["Posição"] = Idade_20["Posição"].replace(dic, regex=True)

colunas = ['Posição', 'Localidade', 'UF', '2010']

Idade_20 = Idade_20 [colunas].copy()

Idade_20 = Idade_20.fillna(0).copy()

Idade_2010 = Idade_20.pivot_table(index=['Localidade', 'UF'], columns= "Posição", values= ['2010'], aggfunc='sum')

Idade_2010 = Idade_2010.reset_index()
Idade_2010.columns = Idade_2010.columns.droplevel(0)

Idade_2010.columns = ['Localidade', 'UF', 'Grupo_de_idade_2010_0_a_4_anos', 
                              'Grupo_de_idade_2010_10_a_14_anos', 'Grupo_de_idade_2010_15_a_19_anos', 
                              'Grupo_de_idade_2010_20_a_24_anos', 'Grupo_de_idade_2010_25_a_29_anos', 
                              'Grupo_de_idade_2010_30_a_39_anos', 'Grupo_de_idade_2010_40_a_49_anos', 
                              'Grupo_de_idade_2010_50_a_59_anos', 'Grupo_de_idade_2010_5_a_9_anos', 
                              'Grupo_de_idade_2010_60_a_69_anos', 'Grupo_de_idade_2010_70_a_mais_anos']

######################################################################################################################

query = ['3.2.1.1.1.1', '3.2.1.1.1.2', '3.2.1.1.1.3', '3.2.1.1.1.4', '3.2.1.1.1.5', 
         '3.2.1.1.1.6', '3.2.1.1.1.7', '3.2.1.1.1.8', '3.2.1.1.1.9', '3.2.1.1.1.10', 
         '3.2.1.2.1.1', '3.2.1.2.1.2', '3.2.1.2.1.3', '3.2.1.2.1.4', '3.2.1.2.1.5', 
         '3.2.1.2.1.6', '3.2.1.2.1.7', '3.2.1.2.1.8', '3.2.1.2.1.9', '3.2.1.2.1.10', 
         '3.2.1.3.1.1', '3.2.1.3.1.2', '3.2.1.3.1.3', '3.2.1.3.1.4', '3.2.1.3.1.5', 
         '3.2.1.3.1.6', '3.2.1.3.1.7', '3.2.1.3.1.8', '3.2.1.3.1.9', '3.2.1.3.1.10', 
         '3.2.1.4.1.1', '3.2.1.4.1.2', '3.2.1.4.1.3', '3.2.1.4.1.4', '3.2.1.4.1.5', 
         '3.2.1.4.1.6', '3.2.1.4.1.7', '3.2.1.4.1.8', '3.2.1.4.1.9', '3.2.1.4.1.10', 
         '3.2.1.5.1.1', '3.2.1.5.1.2', '3.2.1.5.1.3', '3.2.1.5.1.4', '3.2.1.5.1.5', 
         '3.2.1.5.1.6', '3.2.1.5.1.7', '3.2.1.5.1.8', '3.2.1.5.1.9', '3.2.1.5.1.10', 
         '3.2.1.6.1.1', '3.2.1.6.1.2', '3.2.1.6.1.3', '3.2.1.6.1.4', '3.2.1.6.1.5', 
         '3.2.1.6.1.6', '3.2.1.6.1.7', '3.2.1.6.1.8', '3.2.1.6.1.9', '3.2.1.6.1.10']

Cor_20 = Idade_10[Idade_10['Posição'].isin(query)]

dic = {'3.2.1.1.1.1': 'Amarela', '3.2.1.1.1.2': 'Amarela', '3.2.1.1.1.3': 'Amarela', 
       '3.2.1.1.1.4': 'Amarela', '3.2.1.1.1.5': 'Amarela', '3.2.1.1.1.6': 'Amarela', 
       '3.2.1.1.1.7': 'Amarela', '3.2.1.1.1.8': 'Amarela', '3.2.1.1.1.9': 'Amarela', 
       '3.2.1.1.1.10': 'Amarela', '3.2.1.2.1.1': 'Branca', '3.2.1.2.1.2': 'Branca', 
       '3.2.1.2.1.3': 'Branca', '3.2.1.2.1.4': 'Branca', '3.2.1.2.1.5': 'Branca', 
       '3.2.1.2.1.6': 'Branca', '3.2.1.2.1.7': 'Branca', '3.2.1.2.1.8': 'Branca', 
       '3.2.1.2.1.9': 'Branca', '3.2.1.2.1.10': 'Branca', '3.2.1.3.1.1': 'Indígena', 
       '3.2.1.3.1.2': 'Indígena', '3.2.1.3.1.3': 'Indígena', '3.2.1.3.1.4': 'Indígena', 
       '3.2.1.3.1.5': 'Indígena', '3.2.1.3.1.6': 'Indígena', '3.2.1.3.1.7': 'Indígena', 
       '3.2.1.3.1.8': 'Indígena', '3.2.1.3.1.9': 'Indígena', '3.2.1.3.1.10': 'Indígena', 
       '3.2.1.4.1.1': 'Parda', '3.2.1.4.1.2': 'Parda', '3.2.1.4.1.3': 'Parda', 
       '3.2.1.4.1.4': 'Parda', '3.2.1.4.1.5': 'Parda', '3.2.1.4.1.6': 'Parda', 
       '3.2.1.4.1.7': 'Parda', '3.2.1.4.1.8': 'Parda', '3.2.1.4.1.9': 'Parda', 
       '3.2.1.4.1.10': 'Parda', '3.2.1.5.1.1': 'Preta', '3.2.1.5.1.2': 'Preta', 
       '3.2.1.5.1.3': 'Preta', '3.2.1.5.1.4': 'Preta', '3.2.1.5.1.5': 'Preta', 
       '3.2.1.5.1.6': 'Preta', '3.2.1.5.1.7': 'Preta', '3.2.1.5.1.8': 'Preta', 
       '3.2.1.5.1.9': 'Preta', '3.2.1.5.1.10': 'Preta', '3.2.1.6.1.1': 'Sem declaração de cor', 
       '3.2.1.6.1.2': 'Sem declaração de cor', '3.2.1.6.1.3': 'Sem declaração de cor', 
       '3.2.1.6.1.4': 'Sem declaração de cor', '3.2.1.6.1.5': 'Sem declaração de cor', 
       '3.2.1.6.1.6': 'Sem declaração de cor', '3.2.1.6.1.7': 'Sem declaração de cor', 
       '3.2.1.6.1.8': 'Sem declaração de cor', '3.2.1.6.1.9': 'Sem declaração de cor', 
       '3.2.1.6.1.10': 'Sem declaração de cor'}

dic = {r"\b{}\b".format(k): v for k, v in dic.items()}

Cor_20["Posição"] = Cor_20["Posição"].replace(dic, regex=True)

colunas = ['Posição', 'Localidade', 'UF', '2010']

Cor_30 = Cor_20 [colunas].copy()

Cor_30 = Cor_30.fillna(0).copy()

Cor_30 = Cor_30.replace(99999999999992, 0).copy()

Cor_40 = Cor_30.pivot_table(index=['Localidade', 'UF'], columns= "Posição", values= ['2010'], aggfunc='sum')

Cor_40 = Cor_40.reset_index()
Cor_40.columns = Cor_40.columns.droplevel(0)

Cor_40.columns = ['Localidade', 'UF', 'Cor_Amarela', 'Cor_Branca', 'Cor_Indígena', 'Cor_Parda', 'Cor_Preta', 'Sem_Declaração_de_Cor']

Cor_40['Total'] = Cor_40['Cor_Amarela'] + Cor_40['Cor_Branca'] + Cor_40['Cor_Indígena'] + Cor_40['Cor_Parda'] + Cor_40['Cor_Preta'] + Cor_40['Sem_Declaração_de_Cor']

Cor_40['Cor_Amarela'] = Cor_40['Cor_Amarela'] / Cor_40['Total'] * 100
Cor_40['Cor_Branca'] = Cor_40['Cor_Branca'] / Cor_40['Total'] * 100
Cor_40['Cor_Indígena'] = Cor_40['Cor_Indígena'] / Cor_40['Total'] * 100
Cor_40['Cor_Parda'] = Cor_40['Cor_Parda'] / Cor_40['Total'] * 100
Cor_40['Cor_Preta'] = Cor_40['Cor_Preta'] / Cor_40['Total'] * 100
Cor_40['Sem_Declaração_de_Cor'] = Cor_40['Sem_Declaração_de_Cor'] / Cor_40['Total'] * 100

Cor_40.drop(['Total'], axis=1, inplace=True)

Cor_40.columns = ['Localidade', 'UF', 'Cor_Amarela_%_2010', 'Cor_Branca_%_2010', 'Cor_Indígena_%_2010', 'Cor_Parda_%_2010', 'Cor_Preta_%_2010', 'Sem_Declaração_de_Cor_%_2010']

Idade_Cor_2010 = pd.merge(Idade_2010, Cor_40,
                            how='left', on=['Localidade', 'UF'])

Idade_Cor_2010.columns = ['Localidade', 'UF', 'Idade_0_a_4_2010', 'Idade_5_a_9_2010', 
                          'Idade_10_a_14_2010', 'Idade_15_a_19_2010', 'Idade_20_a_24_2010', 
                          'Idade_25_a_29_2010', 'Idade_30_a_39_2010', 'Idade_40_a_49_2010',
                          'Idade_50_a_59_2010', 'Idade_60_a_69_2010','Idade_70_a_mais_2010', 
                          'Cor_Amarela_%_2010', 'Cor_Branca_%_2010', 'Cor_Indígena_%_2010', 
                          'Cor_Parda_%_2010', 'Cor_Preta_%_2010', 'Sem_Declaração_de_Cor_%_2010']

Idade_Cor_2010.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Localidade,UF,Idade_0_a_4_2010,Idade_5_a_9_2010,Idade_10_a_14_2010,Idade_15_a_19_2010,Idade_20_a_24_2010,Idade_25_a_29_2010,Idade_30_a_39_2010,Idade_40_a_49_2010,Idade_50_a_59_2010,Idade_60_a_69_2010,Idade_70_a_mais_2010,Cor_Amarela_%_2010,Cor_Branca_%_2010,Cor_Indígena_%_2010,Cor_Parda_%_2010,Cor_Preta_%_2010,Sem_Declaração_de_Cor_%_2010
0,Abadia de Goiás,GO,505.0,653.0,651.0,600.0,609.0,1111.0,917.0,656.0,566.0,363.0,245.0,2.344205,41.642400,0.116482,51.164822,4.732091,0.0
1,Abadia dos Dourados,MG,412.0,548.0,514.0,466.0,523.0,1034.0,1018.0,815.0,406.0,597.0,371.0,0.568522,69.688809,0.044883,25.852783,3.845003,0.0
2,Abadiânia,GO,1052.0,1469.0,1510.0,1385.0,1282.0,2624.0,2145.0,1410.0,1214.0,967.0,699.0,4.238515,38.778465,0.125049,53.119652,3.738318,0.0
3,Abaetetuba,PA,13094.0,16282.0,16571.0,14892.0,13323.0,20366.0,13430.0,9065.0,14090.0,5685.0,4302.0,0.551571,21.666228,0.073211,70.925943,6.783046,0.0
4,Abaeté,MG,1314.0,1910.0,1845.0,1817.0,1674.0,3193.0,3405.0,2708.0,1545.0,1777.0,1502.0,0.800356,53.201423,0.040018,40.506892,5.451312,0.0

##**Captura IBGE - Censo Indicadores Sociais**

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/Censo INDICADORES SOCIAIS/'

Indicadores_10 = pd.read_csv(folder_path + "Censo-AC.csv", sep=',', encoding="UTF-8")
Indicadores_10 = Indicadores_10.iloc[0:0,:].copy() 

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    Indicadores_05 = pd.read_csv(nome_do_arquivo, sep=',', encoding="UTF-8")
    Indicadores_05 ['UF']=str(nome_do_arquivo[-6:-4])
    Indicadores_10 = pd.concat([Indicadores_10, Indicadores_05], axis=0, sort=False)

query = ['19.5.2.1.1', '19.5.2.1.2', '19.5.2.1.3', '19.9.2']

Indicadores_20 = Indicadores_10[Indicadores_10['Posição'].isin(query)]

dic = {'19.5.2.1.1': 'Saneamento_Adequado_%_2010', 
       '19.5.2.1.2': 'Saneamento_Inadequado_%_2010', 
       '19.5.2.1.3': 'Saneamento_Semi-adequado_%_2010', 
       '19.9.2': 'Taxa_analfabetismo_população_15_anos_ou_mais_%_2010'}

dic = {r"\b{}\b".format(k): v for k, v in dic.items()}

Indicadores_20["Posição"] = Indicadores_20["Posição"].replace(dic, regex=True)

colunas = ['Posição', 'Localidade', 'UF', '2010']

Indicadores_20 = Indicadores_20 [colunas].copy()

Indicadores_20 = Indicadores_20.fillna(0).copy()

#Indicadores_2010 = Indicadores_20.pivot(index=['Localidade', 'UF'], columns= 'Posição', values= ['2010']).copy()
Indicadores_2010 = Indicadores_20.pivot_table(index=['Localidade', 'UF'], columns= "Posição", values= ['2010'], aggfunc='sum')

Indicadores_2010 = Indicadores_2010.reset_index()
Indicadores_2010.columns = Indicadores_2010.columns.droplevel(0)

colunas = ['Localidade', 'UF', 'Saneamento_Adequado_%_2010', 
           'Saneamento_Inadequado_%_2010', 'Saneamento_Semi-adequado_%_2010', 
           'Taxa_analfabetismo_população_15_anos_ou_mais_%_2010']

Indicadores_2010.columns = colunas

Indicadores_2010 ['Saneamento_Adequado_%_2010'] = Indicadores_2010 ['Saneamento_Adequado_%_2010'].replace('-', 0).copy()
Indicadores_2010 ['Saneamento_Inadequado_%_2010'] = Indicadores_2010 ['Saneamento_Inadequado_%_2010'].replace('-', 0).copy()
Indicadores_2010 ['Saneamento_Semi-adequado_%_2010'] = Indicadores_2010 ['Saneamento_Semi-adequado_%_2010'].replace('-', 0).copy()
Indicadores_2010 ['Taxa_analfabetismo_população_15_anos_ou_mais_%_2010'] = Indicadores_2010 ['Taxa_analfabetismo_população_15_anos_ou_mais_%_2010'].replace('-', 0).copy()

Indicadores_2010 ['Saneamento_Adequado_%_2010'] = Indicadores_2010 ['Saneamento_Adequado_%_2010'].fillna(0).copy()
Indicadores_2010 ['Saneamento_Inadequado_%_2010'] = Indicadores_2010 ['Saneamento_Inadequado_%_2010'].fillna(0).copy()
Indicadores_2010 ['Saneamento_Semi-adequado_%_2010'] = Indicadores_2010 ['Saneamento_Semi-adequado_%_2010'].fillna(0).copy()
Indicadores_2010 ['Taxa_analfabetismo_população_15_anos_ou_mais_%_2010'] = Indicadores_2010 ['Taxa_analfabetismo_população_15_anos_ou_mais_%_2010'].fillna(0).copy()
                                                                                             
Indicadores_2010 ['Saneamento_Adequado_%_2010'] = Indicadores_2010 ['Saneamento_Adequado_%_2010'].astype('float64')
Indicadores_2010 ['Saneamento_Inadequado_%_2010'] = Indicadores_2010 ['Saneamento_Inadequado_%_2010'].astype('float64')
Indicadores_2010 ['Saneamento_Semi-adequado_%_2010'] = Indicadores_2010 ['Saneamento_Semi-adequado_%_2010'].astype('float64')
Indicadores_2010 ['Taxa_analfabetismo_população_15_anos_ou_mais_%_2010'] = Indicadores_2010 ['Taxa_analfabetismo_população_15_anos_ou_mais_%_2010'].astype('float64')

Indicadores_2010.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Localidade,UF,Saneamento_Adequado_%_2010,Saneamento_Inadequado_%_2010,Saneamento_Semi-adequado_%_2010,Taxa_analfabetismo_população_15_anos_ou_mais_%_2010
0,Abadia de Goiás,GO,33.8,10.5,55.7,7.8
1,Abadia dos Dourados,MG,58.8,33.1,8.2,9.1
2,Abadiânia,GO,67.1,15.1,17.9,10.8
3,Abaetetuba,PA,6.6,34.7,58.7,13.7
4,Abaeté,MG,81.7,10.3,8.0,8.7

##**Compilação IBGE - Cidades**

In [ ]:
colunas = ['Localidade', 'UF']

a = Indicadores_2010 [colunas].copy()
b = Idade_Cor_2010 [colunas].copy()
c = Dengue_2012 [colunas].copy()
d = Educacao_2019 [colunas].copy()
e = Financas_2017 [colunas].copy()
f = IDH_2010 [colunas].copy()
g = Educacao_30 [colunas].copy()
h = Panorama_Municipal_2010_2019 [colunas].copy()
i = PIB_2019 [colunas].copy()
j = Pobreza_2003 [colunas].copy()
k = Saneamento_2017 [colunas].copy()

a.columns = colunas
b.columns = colunas
c.columns = colunas
d.columns = colunas
e.columns = colunas
f.columns = colunas
g.columns = colunas
h.columns = colunas
i.columns = colunas
j.columns = colunas
k.columns = colunas

Cidades_Mestre = pd.concat([a, b, c, d, e, f, g, h, i, j, k], axis=0, sort=False)

Cidades_Mestre = Cidades_Mestre.drop_duplicates()

Cidades_Mestre.columns = colunas

Cidades_Mestre.head()

            Localidade  UF
0      Abadia de Goiás  GO
1  Abadia dos Dourados  MG
2            Abadiânia  GO
3           Abaetetuba  PA
4               Abaeté  MG

##**Fusão Tabelas IBGE**

In [ ]:
Tabelao_IBGE = pd.merge(Cidades_Mestre, Saneamento_2017,
                        how='left', on=['Localidade', 'UF'])

Tabelao_IBGE = pd.merge(Tabelao_IBGE, Pobreza_2003,
                        how='left', on=['Localidade', 'UF'])

Tabelao_IBGE = pd.merge(Tabelao_IBGE, PIB_2019,
                        how='left', on=['Localidade', 'UF'])

Tabelao_IBGE = pd.merge(Tabelao_IBGE, Panorama_Municipal_2010_2019,
                        how='left', on=['Localidade', 'UF'])

Tabelao_IBGE = pd.merge(Tabelao_IBGE, Educacao_30,
                        how='left', on=['Localidade', 'UF'])

Tabelao_IBGE = pd.merge(Tabelao_IBGE, IDH_2010,
                        how='left', on=['Localidade', 'UF'])

Tabelao_IBGE = pd.merge(Tabelao_IBGE, Financas_2017,
                        how='left', on=['Localidade', 'UF'])

Tabelao_IBGE = pd.merge(Tabelao_IBGE, Educacao_2019,
                        how='left', on=['Localidade', 'UF'])

Tabelao_IBGE = pd.merge(Tabelao_IBGE, Dengue_2012,
                        how='left', on=['Localidade', 'UF'])

Tabelao_IBGE = pd.merge(Tabelao_IBGE, Idade_Cor_2010,
                        how='left', on=['Localidade', 'UF'])

Tabelao_IBGE = pd.merge(Tabelao_IBGE, Indicadores_2010,
                        how='left', on=['Localidade', 'UF'])

Tabelao_IBGE.head()

,Localidade,UF,Saneamento_Edificios_Abastecidos_Agua_2017,Saneamento_Edificios_Esgotados_2017,Pobreza_%_2003,Gini_2003,PIB_per_capita_2019,Rendimento_mensal_per_capita_Até_meio_SM_%_2010,Saneamento_Esgotamento_adequado_%_2010,Urbanização_%_vias_públicas_2010,Mortalidade_infantil_PER_MIL_2012_2014,Educacao_Anos_finais_Fundamental_2015,Educacao_Anos_iniciais_Fundamental_2015,Rendimento_médio_mensal_SM_2015,Internações_Diarreia_PER_MIL_2016,População_ocupada_%_2019,Educação_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_%_2010,Educação_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_%_2010,Educação_10_anos_ou_mais_Médio_completo_e_superior_incompleto_%_2010,Educação_10_anos_ou_mais_Superior_%_completo_2010,Educação_10_anos_ou_mais_Ocupada_%_2010,Educação_10_anos_ou_mais_Não_ocupada_%_2010,IDH_2010,Despesas_orçamentárias_empenhadas_2017,Indice_Educacao_Médio_Pública_2019,Indice_Educacao_Fundamental_Anos_finais_Pública_2019,Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019,Notificações_Dengue_2012,Idade_0_a_4_2010,Idade_5_a_9_2010,Idade_10_a_14_2010,Idade_15_a_19_2010,Idade_20_a_24_2010,Idade_25_a_29_2010,Idade_30_a_39_2010,Idade_40_a_49_2010,Idade_50_a_59_2010,Idade_60_a_69_2010,Idade_70_a_mais_2010,Cor_Amarela_%_2010,Cor_Branca_%_2010,Cor_Indígena_%_2010,Cor_Parda_%_2010,Cor_Preta_%_2010,Sem_Declaração_de_Cor_%_2010,Saneamento_Adequado_%_2010,Saneamento_Inadequado_%_2010,Saneamento_Semi-adequado_%_2010,Taxa_analfabetismo_população_15_anos_ou_mais_%_2010
0,Abadia de Goiás,GO,3015.0,1134.0,37.83,0.40,23061.21,30.6,35.0,0.0,18.6,4.4,5.5,2.1,0.5,22.6,55.710594,19.621016,19.000861,5.650301,60.172265,39.827735,0.708,3.019089e+07,4.6,4.8,5.9,9.0,505.0,653.0,651.0,600.0,609.0,1111.0,917.0,656.0,566.0,363.0,245.0,2.344205,41.642400,0.116482,51.164822,4.732091,0.0,33.8,10.5,55.7,7.8
1,Abadia dos Dourados,MG,2255.0,2168.0,34.50,0.41,18254.66,35.0,59.9,36.3,15.3,5.0,6.8,1.7,1.7,26.0,62.810058,20.013592,12.062521,4.858987,56.371050,43.611961,0.689,1.879352e+07,0.0,5.6,7.3,1.0,412.0,548.0,514.0,466.0,523.0,1034.0,1018.0,815.0,406.0,597.0,371.0,0.568522,69.688809,0.044883,25.852783,3.845003,0.0,58.8,33.1,8.2,9.1
2,Abadiânia,GO,0.0,0.0,38.85,0.42,17302.04,35.9,77.5,0.9,17.4,4.9,5.1,1.8,0.1,11.7,59.061597,17.307835,19.464828,3.513453,54.725372,45.274628,0.689,4.051808e+07,0.0,4.9,5.8,7.0,1052.0,1469.0,1510.0,1385.0,1282.0,2624.0,2145.0,1410.0,1214.0,967.0,699.0,4.238515,38.778465,0.125049,53.119652,3.738318,0.0,67.1,15.1,17.9,10.8
3,Abaetetuba,PA,5277.0,0.0,51.34,0.40,9480.05,52.6,16.5,5.1,14.0,3.4,4.4,1.8,4.2,7.5,62.683030,15.593946,18.229222,2.926718,46.680888,53.319112,0.628,2.235550e+08,3.6,3.6,4.7,228.0,13094.0,16282.0,16571.0,14892.0,13323.0,20366.0,13430.0,9065.0,14090.0,5685.0,4302.0,0.551571,21.666228,0.073211,70.925943,6.783046,0.0,6.6,34.7,58.7,13.7
4,Abaeté,MG,9689.0,163.0,36.17,0.42,22262.55,33.4,85.0,13.9,13.1,4.3,6.9,1.7,0.8,19.8,66.133831,14.386566,13.917604,5.118249,54.903938,45.096062,0.698,4.077422e+07,3.9,4.9,6.9,0.0,1314.0,1910.0,1845.0,1817.0,1674.0,3193.0,3405.0,2708.0,1545.0,1777.0,1502.0,0.800356,53.201423,0.040018,40.506892,5.451312,0.0,81.7,10.3,8.0,8.7

In [ ]:
from unicodedata import normalize
def remover_acentos(txt):
    return normalize('NFKD', txt).encode('ASCII', 'ignore').decode('ASCII')
if __name__ == '__main__':
    from doctest import testmod
    testmod()

PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check:
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/usr/lib/python3.7/doctest.py", line 1487, in run
    sys.settrace(save_trace)

In [ ]:
Tabelao_IBGE.rename(columns={'Localidade': 'NM_MUNICIPIO', 'UF': 'SG_UF'}, inplace = True)

Tabelao_IBGE['NM_MUNICIPIO'] = Tabelao_IBGE['NM_MUNICIPIO'].str.upper()
Tabelao_IBGE['NM_MUNICIPIO'] = Tabelao_IBGE['NM_MUNICIPIO'].agg(lambda x: remover_acentos(x), axis=0)
Tabelao_IBGE['NM_MUNICIPIO'].replace(to_replace="D'", value=r"D ", regex=True, inplace=True)
Tabelao_IBGE['NM_MUNICIPIO'].replace(to_replace="-", value=r" ", regex=True, inplace=True)

Tabelao_IBGE['NM_MUNICIPIO'].replace(to_replace="CAMACAN", value=r"CAMACA", regex=True, inplace=True)
Tabelao_IBGE['NM_MUNICIPIO'].replace(to_replace="DONA EUZEBIA", value=r"DONA EUSEBIA", regex=True, inplace=True)
Tabelao_IBGE['NM_MUNICIPIO'].replace(to_replace="SAO TOME DAS LETRAS", value=r"SAO THOME DAS LETRAS", regex=True, inplace=True)
Tabelao_IBGE['NM_MUNICIPIO'].replace(to_replace="ELDORADO DO CARAJAS", value=r"ELDORADO DOS CARAJAS", regex=True, inplace=True)
Tabelao_IBGE['NM_MUNICIPIO'].replace(to_replace="SANTA IZABEL DO PARA", value=r"SANTA ISABEL DO PARA", regex=True, inplace=True)
Tabelao_IBGE['NM_MUNICIPIO'].replace(to_replace="SANT'ANA DO LIVRAMENTO", value=r"SANT ANA DO LIVRAMENTO", regex=True, inplace=True)
Tabelao_IBGE['NM_MUNICIPIO'].replace(to_replace="AMPARO DO SAO FRANCISCO", value=r"AMPARO DE SAO FRANCISCO", regex=True, inplace=True)
Tabelao_IBGE['NM_MUNICIPIO'].replace(to_replace="GRACHO CARDOSO", value=r"GRACCHO CARDOSO", regex=True, inplace=True)
Tabelao_IBGE['NM_MUNICIPIO'].replace(to_replace="SAO LUIZ DO PARAITINGA", value=r"SAO LUIS DO PARAITINGA", regex=True, inplace=True)

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/'

Tabelao_IBGE.to_excel(folder_path + 'Tabelao_IBGE.xlsx', sheet_name='Tabelao_IBGE', index=False)

#**Dados SUS**

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/'

SUS_rl_Estab_Complementar_202201 = pd.read_csv(folder_path + "/rlEstabComplementar202201.csv", sep=';', encoding="UTF-8")
tbLeito202201 = pd.read_csv(folder_path + "/tbLeito202201.csv", sep=';', encoding="UTF-8")

SUS_rl_Estab_Complementar_202201 = SUS_rl_Estab_Complementar_202201 [['CO_UNIDADE', 'CO_LEITO', 'CO_TIPO_LEITO', 'QT_EXIST', 'QT_CONTR', 'QT_SUS']].copy()

SUS_rl_Estab_Complementar_202201 = pd.merge(SUS_rl_Estab_Complementar_202201, tbLeito202201,
                            how='left', on='CO_LEITO')

SUS_LEITOS = SUS_rl_Estab_Complementar_202201.fillna(0).copy()

SUS_LEITOS.head()

,CO_UNIDADE,CO_LEITO,CO_TIPO_LEITO,QT_EXIST,QT_CONTR,QT_SUS,DS_LEITO,TP_LEITO
0,3107405661943,11,1,1,0.0,0,OFTALMOLOGIA,1
1,3107405661943,15,1,1,0.0,0,PLASTICA,1
2,3136703126277,7,7,2,0.0,0,CIRURGICO/DIAGNOSTICO/TERAPEUTICO,7
3,2918409192484,13,1,6,0.0,6,ORTOPEDIATRAUMATOLOGIA,1
4,2403807206933,33,2,5,0.0,5,CLINICA GERAL,2

In [ ]:
folder_path_2 = '/content/drive/MyDrive/Pos/tbestab/'
Tab_Mun_40 = pd.read_csv(folder_path_2 + "tbEstabelecimento201708.csv", sep=';', encoding="UTF-8")

Tab_Mun_40 = Tab_Mun_40 [['CO_UNIDADE', 'CO_MUNICIPIO_GESTOR', 'CO_CEP']].copy()

lista_de_arquivos = glob.glob(folder_path_2 +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    Tab_Mun_35 = pd.read_csv(nome_do_arquivo, sep=';', encoding="UTF-8")
    Tab_Mun_35 = Tab_Mun_35 [['CO_UNIDADE', 'CO_MUNICIPIO_GESTOR', 'CO_CEP']].copy()
    Tab_Mun_40 = pd.concat([Tab_Mun_40, Tab_Mun_35], axis=0, sort=False)

Tab_Mun_40 = Tab_Mun_40.drop_duplicates()
Tab_Mun_40.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (15,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,14,15,40,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,15,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,36,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,15,36,40,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,15,36,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,12,13,14,15,35,36,38,40,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,14,15,36,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (15,36,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,39,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (39,40,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,36,39,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,15,36,39,40,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,14,36,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (0,13,14,15,36,38,39,40,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

      CO_UNIDADE  CO_MUNICIPIO_GESTOR    CO_CEP
0  4125509315128               412550  83030490
1  4208209307869               420820  88303000
2  4312909314776               431290  95340000
3  3135809311157               313580  39960000
4  3550309317724               355030   4617000

In [ ]:
Tab_Mun_50 = Tab_Mun_40.copy()
Tab_Mun_50.columns = ['CO_UNIDADE', 'CO_MUNICIPIO', 'CO_CEP']

tbMunicipio202201 = pd.read_csv(folder_path + "tbMunicipio202201.csv", sep=';', encoding="UTF-8")

tbMunicipio202201 = tbMunicipio202201 [['CO_MUNICIPIO', 'NO_MUNICIPIO', 'CO_SIGLA_ESTADO']].copy()

Tab_Mun_50['CO_MUNICIPIO'] = Tab_Mun_50['CO_MUNICIPIO'].astype(str)
tbMunicipio202201['CO_MUNICIPIO'] = tbMunicipio202201['CO_MUNICIPIO'].astype(str)

Tab_Mun_50 = pd.merge(Tab_Mun_50, tbMunicipio202201,
                      how='left', on='CO_MUNICIPIO')

Tab_Mun_50 = Tab_Mun_50.drop_duplicates().copy()

Tab_Mun_50.head()

      CO_UNIDADE CO_MUNICIPIO    CO_CEP          NO_MUNICIPIO CO_SIGLA_ESTADO
0  4125509315128       412550  83030490  SAO JOSE DOS PINHAIS              PR
1  4208209307869       420820  88303000                ITAJAI              SC
2  4312909314776       431290  95340000          NOVA BASSANO              RS
3  3135809311157       313580  39960000         JEQUITINHONHA              MG
4  3550309317724       355030   4617000             SAO PAULO              SP

In [ ]:
Tab_Mun_50['CO_UNIDADE'] = Tab_Mun_50['CO_UNIDADE'].astype(str)
SUS_LEITOS['CO_UNIDADE'] = SUS_LEITOS['CO_UNIDADE'].astype(str)

Tab_Leitos_10 = pd.merge(SUS_LEITOS, Tab_Mun_50,
                      how='left', on='CO_UNIDADE')

Tab_Leitos_20 = Tab_Leitos_10.drop_duplicates()
Tab_Leitos_20.head()

,CO_UNIDADE,CO_LEITO,CO_TIPO_LEITO,QT_EXIST,QT_CONTR,QT_SUS,DS_LEITO,TP_LEITO,CO_MUNICIPIO,CO_CEP,NO_MUNICIPIO,CO_SIGLA_ESTADO
0,3107405661943,11,1,1,0.0,0,OFTALMOLOGIA,1,310740,35600000,BOM DESPACHO,MG
1,3107405661943,15,1,1,0.0,0,PLASTICA,1,310740,35600000,BOM DESPACHO,MG
2,3136703126277,7,7,2,0.0,0,CIRURGICO/DIAGNOSTICO/TERAPEUTICO,7,313670,36016230,JUIZ DE FORA,MG
4,2918409192484,13,1,6,0.0,6,ORTOPEDIATRAUMATOLOGIA,1,291840,48900140,JUAZEIRO,BA
6,2403807206933,33,2,5,0.0,5,CLINICA GERAL,2,240380,59335000,FLORANIA,RN

In [ ]:
Tab_Leitos_20.columns

Index(['CO_UNIDADE', 'CO_LEITO', 'CO_TIPO_LEITO', 'QT_EXIST', 'QT_CONTR',
       'QT_SUS', 'DS_LEITO', 'TP_LEITO', 'CO_MUNICIPIO', 'CO_CEP',
       'NO_MUNICIPIO', 'CO_SIGLA_ESTADO'],
      dtype='object')

In [ ]:
Tab_Leitos_30 = Tab_Leitos_20 [['NO_MUNICIPIO', 'CO_SIGLA_ESTADO', 'CO_MUNICIPIO',
                                'QT_EXIST', 'QT_CONTR', 'QT_SUS']]
Tab_Leitos_30.head()

   NO_MUNICIPIO CO_SIGLA_ESTADO CO_MUNICIPIO  QT_EXIST  QT_CONTR  QT_SUS
0  BOM DESPACHO              MG       310740         1       0.0       0
1  BOM DESPACHO              MG       310740         1       0.0       0
2  JUIZ DE FORA              MG       313670         2       0.0       0
4      JUAZEIRO              BA       291840         6       0.0       6
6      FLORANIA              RN       240380         5       0.0       5

In [ ]:
Tab_Leitos_40 = pd.pivot_table(Tab_Leitos_30, values=['QT_EXIST', 'QT_CONTR', 'QT_SUS'], index=['NO_MUNICIPIO', 'CO_SIGLA_ESTADO', 'CO_MUNICIPIO'],
                       aggfunc="sum")

Tab_Leitos_40 = Tab_Leitos_40.reset_index()

Tab_Leitos_40.head()

,NO_MUNICIPIO,CO_SIGLA_ESTADO,CO_MUNICIPIO,QT_CONTR,QT_EXIST,QT_SUS
0,ABADIA DOS DOURADOS,MG,310010,0.0,29,21
1,ABADIANIA,GO,520010,0.0,9,9
2,ABAETE,MG,310020,0.0,46,41
3,ABAETETUBA,PA,150010,0.0,406,303
4,ABAIARA,CE,230010,0.0,1,1

In [ ]:
dic = {"OLHO D'AGUA DAS FLORES": 'OLHO D AGUA DAS FLORES', 'CAMACAN': 'CAMACA', 
       "DIAS D'AVILA": 'DIAS D AVILA', 'SANTA TERESINHA': 'SANTA TEREZINHA', 
       'XIQUE-XIQUE': 'XIQUE XIQUE', 'ITAPAGE': 'ITAPAJE', "SAO JOAO D'ALIANCA": 'SAO JOAO D ALIANCA', 
       'APICUM-ACU': 'APICUM ACU', 'CONCEICAO DO LAGO-ACU': 'CONCEICAO DO LAGO ACU', 
       "OLHO D'AGUA DAS CUNHAS": 'OLHO D AGUA DAS CUNHAS', 'PINDARE-MIRIM': 'PINDARE MIRIM', 
       'BRASOPOLIS': 'BRAZOPOLIS', 'GUARDA-MOR': 'GUARDA MOR', "GLORIA D'OESTE": 'GLORIA D OESTE', 
       'IGARAPE-ACU': 'IGARAPE ACU', 'IGARAPE-MIRI': 'IGARAPE MIRI', "PAU D'ARCO": 'PAU D ARCO', 
       'SANTA IZABEL DO PARA': 'SANTA ISABEL DO PARA', "OLHO D'AGUA": 'OLHO D AGUA', 
       'BELEM DE SAO FRANCISCO': 'BELEM DO SAO FRANCISCO', 'IGUARACI': 'IGUARACY', 
       'LAGOA DO ITAENGA': 'LAGOA DE ITAENGA', "DIAMANTE D'OESTE": 'DIAMANTE D OESTE', 
       "PEROLA D'OESTE": 'PEROLA D OESTE', "SAO JORGE D'OESTE": 'SAO JORGE D OESTE', 
       'TRAJANO DE MORAIS': 'TRAJANO DE MORAES', 'VARRE-SAI': 'VARRE SAI', 
       'GOVERNADOR DIX-SEPT ROSADO': 'GOVERNADOR DIX SEPT ROSADO', "LAGOA D'ANTA": 'LAGOA D ANTA', 
       "OLHO-D'AGUA DO BORGES": 'OLHO D AGUA DO BORGES', 'VENHA-VER': 'VENHA VER', 
       "ALTA FLORESTA D'OESTE": 'ALTA FLORESTA D OESTE', "ALVORADA D'OESTE": 'ALVORADA D OESTE', 
       "ESPIGAO D'OESTE": 'ESPIGAO D OESTE', 'JI-PARANA': 'JI PARANA', 
       "MACHADINHO D'OESTE": 'MACHADINHO D OESTE', "NOVA BRASILANDIA D'OESTE": 'NOVA BRASILANDIA D OESTE', 
       "SANTA LUZIA D'OESTE": 'SANTA LUZIA D OESTE', "SAO FELIPE D'OESTE": 'SAO FELIPE D OESTE', 
       'NAO-ME-TOQUE': 'NAO ME TOQUE', 'SANTANA DO LIVRAMENTO': 'SANT ANA DO LIVRAMENTO', 
       'XANGRI-LA': 'XANGRI LA', "ITAPORANGA D'AJUDA": 'ITAPORANGA D AJUDA', 
       "APARECIDA D'OESTE": 'APARECIDA D OESTE', 'BIRITIBA-MIRIM': 'BIRITIBA MIRIM', 
       'EMBU-GUACU': 'EMBU GUACU', "ESTRELA D'OESTE": 'ESTRELA D OESTE', 'MOJI MIRIM': 'MOGI MIRIM', 
       "PALMEIRA D'OESTE": 'PALMEIRA D OESTE', 'PARIQUERA-ACU': 'PARIQUERA ACU', 
       "SANTA BARBARA D'OESTE": 'SANTA BARBARA D OESTE',
       "MIRASSOL D'OESTE": "MIRASSOL D OESTE", "POXOREO": "POXOREU", "TOME-ACU": "TOME ACU", 
       "PARATI": "PARATY", "CEARA-MIRIM": "CEARA MIRIM", "GUAJARA-MIRIM": "GUAJARA MIRIM"}                                                                                                

dic = {r"\b{}\b".format(k): v for k, v in dic.items()}

Tab_Leitos_40["NO_MUNICIPIO"] = Tab_Leitos_40["NO_MUNICIPIO"].replace(dic, regex=True)

Tab_Leitos_40.loc[Tab_Leitos_40["CO_MUNICIPIO"]=="251380", 'NO_MUNICIPIO']='SANTA TERESINHA'

Tab_Leitos_40.rename(columns={'NO_MUNICIPIO': 'NM_MUNICIPIO', 'CO_SIGLA_ESTADO': 'SG_UF'}, inplace = True)

Tab_Leitos_40.head()

          NM_MUNICIPIO SG_UF CO_MUNICIPIO  QT_CONTR  QT_EXIST  QT_SUS
0  ABADIA DOS DOURADOS    MG       310010       0.0        29      21
1            ABADIANIA    GO       520010       0.0         9       9
2               ABAETE    MG       310020       0.0        46      41
3           ABAETETUBA    PA       150010       0.0       406     303
4              ABAIARA    CE       230010       0.0         1       1

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/'
Tab_Leitos_40.to_excel(folder_path + 'Tab_Leitos_40.xlsx', sheet_name='Tab_Leitos_40', index=False)

#**Dados COVID**

In [ ]:
covid_01 = pd.DataFrame({"Juntada": [""]})

folder_path = '/content/drive/MyDrive/Pos/COVID/'

lista_de_arquivos = glob.glob(folder_path +'*.csv')

for nome_do_arquivo in lista_de_arquivos:
    covid_00 = pd.read_csv(nome_do_arquivo, sep=';', encoding="UTF-8")
    covid_01 = pd.concat([covid_01, covid_00], axis=0, sort=False)
    print (nome_do_arquivo)

del covid_01['Juntada']

covid_01.head()

/content/drive/MyDrive/Pos/COVID/HIST_PAINEL_COVIDBR_2020_Parte2_20mai2022.csv
/content/drive/MyDrive/Pos/COVID/HIST_PAINEL_COVIDBR_2020_Parte1_20mai2022.csv
/content/drive/MyDrive/Pos/COVID/HIST_PAINEL_COVIDBR_2022_Parte1_20mai2022.csv
/content/drive/MyDrive/Pos/COVID/HIST_PAINEL_COVIDBR_2021_Parte1_20mai2022.csv
/content/drive/MyDrive/Pos/COVID/HIST_PAINEL_COVIDBR_2021_Parte2_20mai2022.csv

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Brasil,NaN,NaN,76.0,NaN,NaN,NaN,2020-08-01,31.0,210147125.0,2707877.0,45392.0,93563.0,1088.0,1865729.0,748585.0,NaN
1,Brasil,NaN,NaN,76.0,NaN,NaN,NaN,2020-08-02,32.0,210147125.0,2733677.0,25800.0,94104.0,541.0,1883677.0,755896.0,NaN
2,Brasil,NaN,NaN,76.0,NaN,NaN,NaN,2020-08-03,32.0,210147125.0,2750318.0,16641.0,94665.0,561.0,1912319.0,743334.0,NaN
3,Brasil,NaN,NaN,76.0,NaN,NaN,NaN,2020-08-04,32.0,210147125.0,2801921.0,51603.0,95819.0,1154.0,1970767.0,735335.0,NaN

In [ ]:
colunas_COVID_01 = ['regiao', 'coduf', 'estado', 'codmun', 'municipio', 
                    'codRegiaoSaude', 'nomeRegiaoSaude', 'data', 'populacaoTCU2019',
                    'casosAcumulado', 'obitosAcumulado']
covid_01 = covid_01 [colunas_COVID_01]

covid_02 = covid_01.dropna(subset=['codmun','municipio'])

covid_02.sort_values(by='data')

covid_02.head()

,regiao,coduf,estado,codmun,municipio,codRegiaoSaude,nomeRegiaoSaude,data,populacaoTCU2019,casosAcumulado,obitosAcumulado
4448,Norte,11.0,RO,110001.0,Alta Floresta D'Oeste,11005.0,ZONA DA MATA,2020-08-01,22945.0,311.0,2.0
4449,Norte,11.0,RO,110001.0,Alta Floresta D'Oeste,11005.0,ZONA DA MATA,2020-08-02,22945.0,322.0,2.0
4450,Norte,11.0,RO,110001.0,Alta Floresta D'Oeste,11005.0,ZONA DA MATA,2020-08-03,22945.0,322.0,2.0
4451,Norte,11.0,RO,110001.0,Alta Floresta D'Oeste,11005.0,ZONA DA MATA,2020-08-04,22945.0,346.0,2.0
4452,Norte,11.0,RO,110001.0,Alta Floresta D'Oeste,11005.0,ZONA DA MATA,2020-08-05,22945.0,354.0,3.0

In [ ]:
query = ['2020-12-31', '2022-05-20']

covid_03 = covid_02[covid_02['data'].isin(query)]

covid_03.head()

,regiao,coduf,estado,codmun,municipio,codRegiaoSaude,nomeRegiaoSaude,data,populacaoTCU2019,casosAcumulado,obitosAcumulado
4600,Norte,11.0,RO,110001.0,Alta Floresta D'Oeste,11005.0,ZONA DA MATA,2020-12-31,22945.0,1288.0,16.0
4753,Norte,11.0,RO,110002.0,Ariquemes,11001.0,VALE DO JAMARI,2020-12-31,107863.0,7870.0,134.0
4906,Norte,11.0,RO,110003.0,Cabixi,11006.0,CONE SUL,2020-12-31,5312.0,187.0,6.0
5059,Norte,11.0,RO,110004.0,Cacoal,11002.0,CAFE,2020-12-31,85359.0,4045.0,57.0
5212,Norte,11.0,RO,110005.0,Cerejeiras,11006.0,CONE SUL,2020-12-31,16323.0,321.0,7.0

In [ ]:
from unicodedata import normalize
def remover_acentos(txt):
    return normalize('NFKD', txt).encode('ASCII', 'ignore').decode('ASCII')
if __name__ == '__main__':
    from doctest import testmod
    testmod()

In [ ]:
covid_03['municipio'] = covid_03['municipio'].str.upper()
covid_03['municipio'] = covid_03['municipio'].agg(lambda x: remover_acentos(x), axis=0)
covid_03['municipio'].replace(to_replace="'", value=r" ", regex=True, inplace=True)
covid_03['municipio'].replace(to_replace="SAO TOME DAS LETRAS", value=r"SAO THOME DAS LETRAS", regex=True, inplace=True)
covid_03['municipio'].replace(to_replace="CAMACAN", value=r"CAMACA", regex=True, inplace=True)
covid_03['municipio'].replace(to_replace="-", value=r" ", regex=True, inplace=True)
covid_03['municipio'].replace(to_replace="ELDORADO DO CARAJAS", value=r"ELDORADO DOS CARAJAS", regex=True, inplace=True)
covid_03['municipio'].replace(to_replace="SANTA IZABEL DO PARA", value=r"SANTA ISABEL DO PARA", regex=True, inplace=True)
covid_03['municipio'].replace(to_replace="GRACHO CARDOSO", value=r"GRACCHO CARDOSO", regex=True, inplace=True)
covid_03['municipio'].replace(to_replace="SAO LUIZ DO PARAITINGA", value=r"SAO LUIS DO PARAITINGA", regex=True, inplace=True)
covid_03['municipio'].replace(to_replace="DONA EUZEBIA", value=r"DONA EUSEBIA", regex=True, inplace=True)

covid_03.rename(columns={'estado': 'SG_UF', 'municipio': 'NM_MUNICIPIO'}, inplace = True)

covid_03.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)
/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,regiao,coduf,SG_UF,codmun,NM_MUNICIPIO,codRegiaoSaude,nomeRegiaoSaude,data,populacaoTCU2019,casosAcumulado,obitosAcumulado
4600,Norte,11.0,RO,110001.0,ALTA FLORESTA D OESTE,11005.0,ZONA DA MATA,2020-12-31,22945.0,1288.0,16.0
4753,Norte,11.0,RO,110002.0,ARIQUEMES,11001.0,VALE DO JAMARI,2020-12-31,107863.0,7870.0,134.0
4906,Norte,11.0,RO,110003.0,CABIXI,11006.0,CONE SUL,2020-12-31,5312.0,187.0,6.0
5059,Norte,11.0,RO,110004.0,CACOAL,11002.0,CAFE,2020-12-31,85359.0,4045.0,57.0
5212,Norte,11.0,RO,110005.0,CEREJEIRAS,11006.0,CONE SUL,2020-12-31,16323.0,321.0,7.0

In [ ]:
#covid_03[covid_03['NM_MUNICIPIO']=='ARES']
covid_03.loc[covid_03["NM_MUNICIPIO"]=="240120", 'NO_MUNICIPIO']='AREZ'

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1684: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = infer_fill_value(value)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [ ]:
covid_07 = pd.pivot_table(covid_03, values=['casosAcumulado', 'obitosAcumulado'], index=['regiao', 'coduf', 'SG_UF', 'codmun', 'NM_MUNICIPIO', 
                                                                                         'codRegiaoSaude', 'nomeRegiaoSaude', 'populacaoTCU2019'],
                          columns=['data'], aggfunc={'casosAcumulado': np.sum, 'obitosAcumulado': np.sum})

covid_07 = covid_07.reset_index()

covid_07.head()

            regiao coduf SG_UF    codmun  NM_MUNICIPIO codRegiaoSaude  \
data
0     Centro-Oeste  50.0    MS  500020.0    AGUA CLARA        50004.0
1     Centro-Oeste  50.0    MS  500025.0   ALCINOPOLIS        50001.0
2     Centro-Oeste  50.0    MS  500060.0       AMAMBAI        50003.0
3     Centro-Oeste  50.0    MS  500070.0     ANASTACIO        50001.0
4     Centro-Oeste  50.0    MS  500080.0  ANAURILANDIA        50003.0

     nomeRegiaoSaude populacaoTCU2019 casosAcumulado             \
data                                      2020-12-31 2022-05-20
0        TRES LAGOAS          15522.0          573.0     4554.0
1       CAMPO GRANDE           5343.0           50.0      812.0
2           DOURADOS          39396.0         1170.0     5843.0
3       CAMPO GRANDE          25135.0         1078.0     3204.0
4           DOURADOS           9035.0           88.0     1128.0

     obitosAcumulado
data      2020-12-31 2022-05-20
0                4.0       69.0
1                2.0       14.0
2               18.0      102.0
3               28.0       92.0
4                2.0       16.0

In [ ]:
covid_07 ['casos_Acum_PER_2020_12_31'] = covid_07['casosAcumulado']['2020-12-31']/covid_07 ['populacaoTCU2019']*100000
covid_07 ['obitos_Acum_PER_2020_12_31'] = covid_07['obitosAcumulado']['2020-12-31']/covid_07 ['populacaoTCU2019']*100000
covid_07 ['casos_Acum_PER_2022-05-20'] = covid_07['casosAcumulado']['2022-05-20']/covid_07 ['populacaoTCU2019']*100000
covid_07 ['obitos_Acum_PER_2022-05-20'] = covid_07['obitosAcumulado']['2022-05-20']/covid_07 ['populacaoTCU2019']*100000

covid_07.drop(['casosAcumulado', 'obitosAcumulado'], axis=1, inplace=True)

covid_07.columns = covid_07.columns.droplevel(1)

# covid_07['NM_MUNICIPIO'].replace(to_replace="ARES", value=r"AREZ", regex=True, inplace=True)

covid_07.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:4150: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)

,regiao,coduf,SG_UF,codmun,NM_MUNICIPIO,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019,casos_Acum_PER_2020_12_31,obitos_Acum_PER_2020_12_31,casos_Acum_PER_2022-05-20,obitos_Acum_PER_2022-05-20
0,Centro-Oeste,50.0,MS,500020.0,AGUA CLARA,50004.0,TRES LAGOAS,15522.0,3691.534596,25.769875,29339.002706,444.530344
1,Centro-Oeste,50.0,MS,500025.0,ALCINOPOLIS,50001.0,CAMPO GRANDE,5343.0,935.803856,37.432154,15197.454614,262.025080
2,Centro-Oeste,50.0,MS,500060.0,AMAMBAI,50003.0,DOURADOS,39396.0,2969.844654,45.689918,14831.454970,258.909534
3,Centro-Oeste,50.0,MS,500070.0,ANASTACIO,50001.0,CAMPO GRANDE,25135.0,4288.840263,111.398448,12747.165307,366.023473
4,Centro-Oeste,50.0,MS,500080.0,ANAURILANDIA,50003.0,DOURADOS,9035.0,973.990039,22.136137,12484.781406,177.089098

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/'
covid_07.to_excel(folder_path+'covid_07.xlsx', sheet_name='covid_07', index=False)

#**Dados Eleitorais - TSE**

In [ ]:
# checar encoding': 'ISO-8859-1

folder_path = '/content/drive/MyDrive/Pos/2020_Resultado_Eleicao_2020/'

import chardet
with open(folder_path+'votacao_candidato_munzona_2020_AC.csv', 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))
result

{'confidence': 0.73, 'encoding': 'ISO-8859-1', 'language': ''}

In [ ]:
DADOS_ELEITORAIS_2020 = pd.read_csv(folder_path+"votacao_candidato_munzona_2020_BRASIL.csv", sep=';', encoding = "ISO-8859-1")

DADOS_ELEITORAIS_2020.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,CD_CARGO,DS_CARGO,SQ_CANDIDATO,NR_CANDIDATO,NM_CANDIDATO,NM_URNA_CANDIDATO,NM_SOCIAL_CANDIDATO,CD_SITUACAO_CANDIDATURA,DS_SITUACAO_CANDIDATURA,CD_DETALHE_SITUACAO_CAND,DS_DETALHE_SITUACAO_CAND,TP_AGREMIACAO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,SQ_COLIGACAO,NM_COLIGACAO,DS_COMPOSICAO_COLIGACAO,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO,ST_VOTO_EM_TRANSITO,QT_VOTOS_NOMINAIS
0,16/01/2022,12:32:02,2020,2,Eleição Ordinária,1,426,ELEIÇÕES MUNICIPAIS 2020,15/11/2020,M,SP,70718,SANTOS,70718,SANTOS,273,13,Vereador,250001089408,36123,DANILO RAFAEL FERREIRA DE MORAIS,DANILO MORAIS JACARÉ,#NULO#,12,APTO,2,DEFERIDO,Partido isolado,36,PTC,Partido Trabalhista Cristão,250000131914,PARTIDO ISOLADO,PTC,4,NÃO ELEITO,N,76
1,16/01/2022,12:32:02,2020,2,Eleição Ordinária,1,426,ELEIÇÕES MUNICIPAIS 2020,15/11/2020,M,SP,61204,ILHA SOLTEIRA,61204,ILHA SOLTEIRA,368,13,Vereador,250001164687,51333,ELIETE ALVES DE CAMPOS,ELIETE CAMPOS,#NULO#,12,APTO,2,DEFERIDO,Partido isolado,51,PATRIOTA,Patriota,250000143385,PARTIDO ISOLADO,PATRIOTA,4,NÃO ELEITO,N,13
2,16/01/2022,12:32:02,2020,2,Eleição Ordinária,1,426,ELEIÇÕES MUNICIPAIS 2020,15/11/2020,M,SP,63770,DIADEMA,63770,DIADEMA,426,13,Vereador,250001119436,55321,TIAGO RIBEIRO DA SILVA,TIAGO RIBEIRO,#NULO#,12,APTO,2,DEFERIDO,Partido isolado,55,PSD,Partido Social Democrático,250000135713,PARTIDO ISOLADO,PSD,5,SUPLENTE,N,6
3,16/01/2022,12:32:02,2020,2,Eleição Ordinária,1,426,ELEIÇÕES MUNICIPAIS 2020,15/11/2020,M,SP,63770,DIADEMA,63770,DIADEMA,329,13,Vereador,250000650027,20222,LEANDRO AUGUSTO SILVA ALVES,PASTOR LEANDRO,#NULO#,12,APTO,2,DEFERIDO,Partido isolado,20,PSC,Partido Social Cristão,250000057769,PARTIDO ISOLADO,PSC,4,NÃO ELEITO,N,107
4,16/01/2022,12:32:02,2020,2,Eleição Ordinária,1,426,ELEIÇÕES MUNICIPAIS 2020,15/11/2020,M,SP,63770,DIADEMA,63770,DIADEMA,329,13,Vereador,250001108656,15190,SÉRGIO MURILO PINTO,SÉRGIO MURILO,#NULO#,12,APTO,2,DEFERIDO,Partido isolado,15,MDB,Movimento Democrático Brasileiro,250000134421,PARTIDO ISOLADO,MDB,4,NÃO ELEITO,N,13

In [ ]:
colunas_2020 = ['NR_TURNO',
                
 'SG_UF',
                
 'SG_UE',
 'NM_UE',
                
 'CD_MUNICIPIO',
 'NM_MUNICIPIO',
                
 'CD_CARGO',
 'DS_CARGO',
                
 'NR_PARTIDO',
 'SG_PARTIDO',
 'NM_PARTIDO',
                
 'CD_SIT_TOT_TURNO',
 'DS_SIT_TOT_TURNO',
                
 'QT_VOTOS_NOMINAIS']

DADOS_ELEITORAIS_2020_2 = DADOS_ELEITORAIS_2020 [colunas_2020]

DADOS_ELEITORAIS_2020_2.head()

,NR_TURNO,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,CD_CARGO,DS_CARGO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO,QT_VOTOS_NOMINAIS
0,1,SP,70718,SANTOS,70718,SANTOS,13,Vereador,36,PTC,Partido Trabalhista Cristão,4,NÃO ELEITO,76
1,1,SP,61204,ILHA SOLTEIRA,61204,ILHA SOLTEIRA,13,Vereador,51,PATRIOTA,Patriota,4,NÃO ELEITO,13
2,1,SP,63770,DIADEMA,63770,DIADEMA,13,Vereador,55,PSD,Partido Social Democrático,5,SUPLENTE,6
3,1,SP,63770,DIADEMA,63770,DIADEMA,13,Vereador,20,PSC,Partido Social Cristão,4,NÃO ELEITO,107
4,1,SP,63770,DIADEMA,63770,DIADEMA,13,Vereador,15,MDB,Movimento Democrático Brasileiro,4,NÃO ELEITO,13

In [ ]:
DADOS_ELEITORAIS_2020_PREFEITOS = DADOS_ELEITORAIS_2020_2[DADOS_ELEITORAIS_2020_2["CD_CARGO"]==11]
DADOS_ELEITORAIS_2020_PREFEITOS.head()
#Somente Prefeitos

,NR_TURNO,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,CD_CARGO,DS_CARGO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO,QT_VOTOS_NOMINAIS
6,1,SP,66893,MAUÁ,66893,MAUÁ,11,Prefeito,55,PSD,Partido Social Democrático,4,NÃO ELEITO,11544
36,1,AL,27022,PARICONHA,27022,PARICONHA,11,Prefeito,15,MDB,Movimento Democrático Brasileiro,4,NÃO ELEITO,2476
42,1,RJ,60011,RIO DE JANEIRO,60011,RIO DE JANEIRO,11,Prefeito,17,PSL,Partido Social Liberal,4,NÃO ELEITO,5344
155,1,AM,2577,MANICORÉ,2577,MANICORÉ,11,Prefeito,45,PSDB,Partido da Social Democracia Brasileira,4,NÃO ELEITO,4837
197,1,PR,77976,QUERÊNCIA DO NORTE,77976,QUERÊNCIA DO NORTE,11,Prefeito,55,PSD,Partido Social Democrático,1,ELEITO,3250

In [ ]:
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS = DADOS_ELEITORAIS_2020_PREFEITOS[DADOS_ELEITORAIS_2020_PREFEITOS["CD_SIT_TOT_TURNO"]==1]

colunas_2020_PREFEITO_ELEITO = ['SG_UF',
                
 'SG_UE',
 'NM_UE',
                
 'CD_MUNICIPIO',
 'NM_MUNICIPIO',
                
 'NR_PARTIDO',
 'SG_PARTIDO',
 'NM_PARTIDO',
                
 'QT_VOTOS_NOMINAIS']

DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS = DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS [colunas_2020_PREFEITO_ELEITO]
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS.head()
#Somente Prefeitos Eleitos

,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,QT_VOTOS_NOMINAIS
197,PR,77976,QUERÊNCIA DO NORTE,77976,QUERÊNCIA DO NORTE,55,PSD,Partido Social Democrático,3250
337,SC,81795,JOINVILLE,81795,JOINVILLE,30,NOVO,Partido Novo,24890
338,PE,25135,PAULISTA,25135,PAULISTA,15,MDB,Movimento Democrático Brasileiro,24655
511,PE,25330,RIACHO DAS ALMAS,25330,RIACHO DAS ALMAS,10,REPUBLICANOS,REPUBLICANOS,9377
684,RS,88366,FAZENDA VILANOVA,88366,FAZENDA VILANOVA,12,PDT,Partido Democrático Trabalhista,1454

In [ ]:
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS.isnull().values.any()

False

In [ ]:
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50 = DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS.groupby(['SG_UF', 'SG_UE', 'NM_UE', "CD_MUNICIPIO", 'NM_MUNICIPIO', 'NR_PARTIDO', 'SG_PARTIDO', 'NM_PARTIDO'], as_index=False)['QT_VOTOS_NOMINAIS'].sum()
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50.head()

,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,QT_VOTOS_NOMINAIS
0,AC,1007,BUJARI,1007,BUJARI,12,PDT,Partido Democrático Trabalhista,3386
1,AC,1015,CAPIXABA,1015,CAPIXABA,25,DEM,Democratas,2627
2,AC,1023,PORTO ACRE,1023,PORTO ACRE,11,PP,PROGRESSISTAS,5415
3,AC,1031,SANTA ROSA DO PURUS,1031,SANTA ROSA DO PURUS,15,MDB,Movimento Democrático Brasileiro,1156
4,AC,1040,MARECHAL THAUMATURGO,1040,MARECHAL THAUMATURGO,55,PSD,Partido Social Democrático,4521

In [ ]:
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50['NM_MUNICIPIO'] = DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50['NM_MUNICIPIO'].str.upper()
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50['NM_MUNICIPIO'] = DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50['NM_MUNICIPIO'].agg(lambda x: remover_acentos(x), axis=0)
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50['NM_MUNICIPIO'].replace(to_replace="-", value=r" ", regex=True, inplace=True)
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50['NM_MUNICIPIO'].replace(to_replace="ALVORADA DO OESTE", value=r"ALVORADA D OESTE", regex=True, inplace=True)
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50['NM_MUNICIPIO'].replace(to_replace="ESPIGAO DO OESTE", value=r"ESPIGAO D OESTE", regex=True, inplace=True)

# TIRAR PREFEITOS CASSADOS E NOVOS ELEITOS:
DESTAQUE = [19, 116, 132, 477, 2011, 2674, 2933, 2992, 4936, 5592, 6033, 7188, 7234, 10006, 11258, 13234, 13390, 13692, 13919, 15431, 15695, 15750, 16071, 16519, 16799, 16870, 17736, 17752, 17817, 17930, 17973, 18236, 18430, 19658, 24430, 28576, 32158, 32379, 34150, 37893, 40150, 40320, 41165, 42200, 44350, 44717, 44830, 45977, 46370, 46639, 46930, 50377, 51551, 55034, 56049, 56278, 56430, 58130, 58181, 58203, 58262, 58459, 58513, 58750, 59153, 62375, 62774, 65714, 66699, 70912, 73156, 73407, 73571, 74586, 75647, 76392, 77232, 77615, 77674, 77895, 77933, 78034, 81876, 83771, 85090, 87831, 89672, 90344, 90557, 90662, 90905, 91006, 91111, 91774, 92347, 92800, 93092, 93394, 94056, 95311, 95958, 96075, 98256, 98612]
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65 = DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50[~DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50['CD_MUNICIPIO'].isin(DESTAQUE)]

DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65.head()

,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,QT_VOTOS_NOMINAIS
0,AC,1007,BUJARI,1007,BUJARI,12,PDT,Partido Democrático Trabalhista,3386
1,AC,1015,CAPIXABA,1015,CAPIXABA,25,DEM,Democratas,2627
2,AC,1023,PORTO ACRE,1023,PORTO ACRE,11,PP,PROGRESSISTAS,5415
3,AC,1031,SANTA ROSA DO PURUS,1031,SANTA ROSA DO PURUS,15,MDB,Movimento Democrático Brasileiro,1156
4,AC,1040,MARECHAL THAUMATURGO,1040,MARECHAL THAUMATURGO,55,PSD,Partido Social Democrático,4521

In [ ]:
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50[DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_50['NM_MUNICIPIO']=='ASSU']

#DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65.loc[DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65["CD_MUNICIPIO"]=="16039", 'NO_MUNICIPIO']='ACU'

,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,QT_VOTOS_NOMINAIS
3677,RN,16039,ASSÚ,16039,ASSU,22,PL,Partido Liberal,16823

In [ ]:
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65.columns = ['SG_UF', 'SG_UE_2020', 'NM_UE_2020', 'CD_MUNICIPIO', 'NM_MUNICIPIO', 'NR_PARTIDO_2020', 'SG_PARTIDO_2020', 'NM_PARTIDO_2020', 'QT_VOTOS_NOMINAIS_2020']

columns_2020 = ['SG_UF', 'CD_MUNICIPIO', 'NM_MUNICIPIO', 'NR_PARTIDO_2020', 'SG_PARTIDO_2020', 'NM_PARTIDO_2020', 'QT_VOTOS_NOMINAIS_2020']

DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65 = DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65 [columns_2020]

dic = {'UNIAO DOS PALMAREZ': 'UNIAO DOS PALMARES',
       'SOUTO SOAREZ': 'SOUTO SOARES', 
       'APUIAREZ': 'APUIARES', 
       'LINHAREZ': 'LINHARES', 
       'GOVERNADOR VALADAREZ': 'GOVERNADOR VALADARES', 
       'MARTINS SOAREZ': 'MARTINS SOARES', 
       'RAUL SOAREZ': 'RAUL SOARES', 
       'COLAREZ': 'COLARES', 
       'TAVAREZ': 'TAVARES', 
       'PALMAREZ': 'PALMARES', 
       'CORONEL DOMINGOS SOAREZ': 'CORONEL DOMINGOS SOARES', 
       'TEIXEIRA SOAREZ': 'TEIXEIRA SOARES', 
       'PALMAREZ DO SUL': 'PALMARES DO SUL', 
       'TAVAREZ': 'TAVARES', 
       'ALVAREZ FLORENCE': 'ALVARES FLORENCE', 
       'ALVAREZ MACHADO': 'ALVARES MACHADO', 
       'PALMAREZ PAULISTA': 'PALMARES PAULISTA'}

dic = {r"\b{}\b".format(k): v for k, v in dic.items()}

DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65.loc[DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65["CD_MUNICIPIO"]==16233, 'NM_MUNICIPIO']='ARES'
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65.loc[DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65["CD_MUNICIPIO"]==16039, 'NM_MUNICIPIO']='ACU'

DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65["NM_MUNICIPIO"] = DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65["NM_MUNICIPIO"].replace(dic, regex=True)

DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65.head()

,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_PARTIDO_2020,SG_PARTIDO_2020,NM_PARTIDO_2020,QT_VOTOS_NOMINAIS_2020
0,AC,1007,BUJARI,12,PDT,Partido Democrático Trabalhista,3386
1,AC,1015,CAPIXABA,25,DEM,Democratas,2627
2,AC,1023,PORTO ACRE,11,PP,PROGRESSISTAS,5415
3,AC,1031,SANTA ROSA DO PURUS,15,MDB,Movimento Democrático Brasileiro,1156
4,AC,1040,MARECHAL THAUMATURGO,55,PSD,Partido Social Democrático,4521

In [ ]:
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65[DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65["CD_MUNICIPIO"]==16039]

,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_PARTIDO_2020,SG_PARTIDO_2020,NM_PARTIDO_2020,QT_VOTOS_NOMINAIS_2020
3677,RN,16039,ACU,22,PL,Partido Liberal,16823

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/'
DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65.to_excel(folder_path+'DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65.xlsx', sheet_name='DADOS_ELEITORAIS', index=False)

# **Fusão Dados COVID com Dados Eleitorais - TSE**

In [ ]:
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS = pd.merge(covid_07, DADOS_ELEITORAIS_2020_PREFEITOS_ELEITOS_65,
                            how='left', on=['SG_UF', 'NM_MUNICIPIO'])

FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS.head()

,regiao,coduf,SG_UF,codmun,NM_MUNICIPIO,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019,casos_Acum_PER_2020_12_31,obitos_Acum_PER_2020_12_31,casos_Acum_PER_2022-05-20,obitos_Acum_PER_2022-05-20,CD_MUNICIPIO,NR_PARTIDO_2020,SG_PARTIDO_2020,NM_PARTIDO_2020,QT_VOTOS_NOMINAIS_2020
0,Centro-Oeste,50.0,MS,500020.0,AGUA CLARA,50004.0,TRES LAGOAS,15522.0,3691.534596,25.769875,29339.002706,444.530344,90034.0,55.0,PSD,Partido Social Democrático,3605.0
1,Centro-Oeste,50.0,MS,500025.0,ALCINOPOLIS,50001.0,CAMPO GRANDE,5343.0,935.803856,37.432154,15197.454614,262.025080,55018.0,25.0,DEM,Democratas,2233.0
2,Centro-Oeste,50.0,MS,500060.0,AMAMBAI,50003.0,DOURADOS,39396.0,2969.844654,45.689918,14831.454970,258.909534,90115.0,45.0,PSDB,Partido da Social Democracia Brasileira,11157.0
3,Centro-Oeste,50.0,MS,500070.0,ANASTACIO,50001.0,CAMPO GRANDE,25135.0,4288.840263,111.398448,12747.165307,366.023473,90131.0,45.0,PSDB,Partido da Social Democracia Brasileira,5976.0
4,Centro-Oeste,50.0,MS,500080.0,ANAURILANDIA,50003.0,DOURADOS,9035.0,973.990039,22.136137,12484.781406,177.089098,90158.0,45.0,PSDB,Partido da Social Democracia Brasileira,2423.0

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/'

CLASSE_PARTIDOS = pd.read_excel(io=folder_path + 'ESPECTRO_POLÍTICO.xlsx', sheet_name="Sheet1")

CLASSE_PARTIDOS_2020 = CLASSE_PARTIDOS.copy()
CLASSE_PARTIDOS_2020.columns = ['NR_PARTIDO_2020', 'SG_PARTIDO_2020', 'PLB_2013_2020', 'ESPECTRO_2020']

CLASSE_PARTIDOS_2020.drop(['SG_PARTIDO_2020'], axis=1, inplace=True)

FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_20 = pd.merge(FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS , CLASSE_PARTIDOS_2020,
                            how='left', on=['NR_PARTIDO_2020'])

FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_20.head()

,regiao,coduf,SG_UF,codmun,NM_MUNICIPIO,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019,casos_Acum_PER_2020_12_31,obitos_Acum_PER_2020_12_31,casos_Acum_PER_2022-05-20,obitos_Acum_PER_2022-05-20,CD_MUNICIPIO,NR_PARTIDO_2020,SG_PARTIDO_2020,NM_PARTIDO_2020,QT_VOTOS_NOMINAIS_2020,PLB_2013_2020,ESPECTRO_2020
0,Centro-Oeste,50.0,MS,500020.0,AGUA CLARA,50004.0,TRES LAGOAS,15522.0,3691.534596,25.769875,29339.002706,444.530344,90034.0,55.0,PSD,Partido Social Democrático,3605.0,6.0,DIREITA_CONSERVADORA
1,Centro-Oeste,50.0,MS,500025.0,ALCINOPOLIS,50001.0,CAMPO GRANDE,5343.0,935.803856,37.432154,15197.454614,262.025080,55018.0,25.0,DEM,Democratas,2233.0,6.4,DIREITA_CONSERVADORA
2,Centro-Oeste,50.0,MS,500060.0,AMAMBAI,50003.0,DOURADOS,39396.0,2969.844654,45.689918,14831.454970,258.909534,90115.0,45.0,PSDB,Partido da Social Democracia Brasileira,11157.0,4.1,DIREITA_CONSERVADORA
3,Centro-Oeste,50.0,MS,500070.0,ANASTACIO,50001.0,CAMPO GRANDE,25135.0,4288.840263,111.398448,12747.165307,366.023473,90131.0,45.0,PSDB,Partido da Social Democracia Brasileira,5976.0,4.1,DIREITA_CONSERVADORA
4,Centro-Oeste,50.0,MS,500080.0,ANAURILANDIA,50003.0,DOURADOS,9035.0,973.990039,22.136137,12484.781406,177.089098,90158.0,45.0,PSDB,Partido da Social Democracia Brasileira,2423.0,4.1,DIREITA_CONSERVADORA

In [ ]:
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_20 ['obitos_Acum_PER_Aumento_2020'] = FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_20 ['obitos_Acum_PER_2022-05-20']  - FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_20 ['obitos_Acum_PER_2020_12_31'] 
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_20.head()

,regiao,coduf,SG_UF,codmun,NM_MUNICIPIO,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019,casos_Acum_PER_2020_12_31,obitos_Acum_PER_2020_12_31,casos_Acum_PER_2022-05-20,obitos_Acum_PER_2022-05-20,CD_MUNICIPIO,NR_PARTIDO_2020,SG_PARTIDO_2020,NM_PARTIDO_2020,QT_VOTOS_NOMINAIS_2020,PLB_2013_2020,ESPECTRO_2020,obitos_Acum_PER_Aumento_2020
0,Centro-Oeste,50.0,MS,500020.0,AGUA CLARA,50004.0,TRES LAGOAS,15522.0,3691.534596,25.769875,29339.002706,444.530344,90034.0,55.0,PSD,Partido Social Democrático,3605.0,6.0,DIREITA_CONSERVADORA,418.760469
1,Centro-Oeste,50.0,MS,500025.0,ALCINOPOLIS,50001.0,CAMPO GRANDE,5343.0,935.803856,37.432154,15197.454614,262.025080,55018.0,25.0,DEM,Democratas,2233.0,6.4,DIREITA_CONSERVADORA,224.592925
2,Centro-Oeste,50.0,MS,500060.0,AMAMBAI,50003.0,DOURADOS,39396.0,2969.844654,45.689918,14831.454970,258.909534,90115.0,45.0,PSDB,Partido da Social Democracia Brasileira,11157.0,4.1,DIREITA_CONSERVADORA,213.219616
3,Centro-Oeste,50.0,MS,500070.0,ANASTACIO,50001.0,CAMPO GRANDE,25135.0,4288.840263,111.398448,12747.165307,366.023473,90131.0,45.0,PSDB,Partido da Social Democracia Brasileira,5976.0,4.1,DIREITA_CONSERVADORA,254.625025
4,Centro-Oeste,50.0,MS,500080.0,ANAURILANDIA,50003.0,DOURADOS,9035.0,973.990039,22.136137,12484.781406,177.089098,90158.0,45.0,PSDB,Partido da Social Democracia Brasileira,2423.0,4.1,DIREITA_CONSERVADORA,154.952961

In [ ]:
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_20['ESPECTRO_2020B'] = FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_20 ['ESPECTRO_2020']

FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_30 = pd.get_dummies(FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_20, columns = ['ESPECTRO_2020B']) # Não dropar a coluna original.

FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_30.head()

,regiao,coduf,SG_UF,codmun,NM_MUNICIPIO,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019,casos_Acum_PER_2020_12_31,obitos_Acum_PER_2020_12_31,casos_Acum_PER_2022-05-20,obitos_Acum_PER_2022-05-20,CD_MUNICIPIO,NR_PARTIDO_2020,SG_PARTIDO_2020,NM_PARTIDO_2020,QT_VOTOS_NOMINAIS_2020,PLB_2013_2020,ESPECTRO_2020,obitos_Acum_PER_Aumento_2020,ESPECTRO_2020B_DIREITA_CONSERVADORA,ESPECTRO_2020B_DIREITA_PROGRESSISTA,ESPECTRO_2020B_ESQUERDA_CONSERVADORA,ESPECTRO_2020B_ESQUERDA_PROGRESSISTA
0,Centro-Oeste,50.0,MS,500020.0,AGUA CLARA,50004.0,TRES LAGOAS,15522.0,3691.534596,25.769875,29339.002706,444.530344,90034.0,55.0,PSD,Partido Social Democrático,3605.0,6.0,DIREITA_CONSERVADORA,418.760469,1,0,0,0
1,Centro-Oeste,50.0,MS,500025.0,ALCINOPOLIS,50001.0,CAMPO GRANDE,5343.0,935.803856,37.432154,15197.454614,262.025080,55018.0,25.0,DEM,Democratas,2233.0,6.4,DIREITA_CONSERVADORA,224.592925,1,0,0,0
2,Centro-Oeste,50.0,MS,500060.0,AMAMBAI,50003.0,DOURADOS,39396.0,2969.844654,45.689918,14831.454970,258.909534,90115.0,45.0,PSDB,Partido da Social Democracia Brasileira,11157.0,4.1,DIREITA_CONSERVADORA,213.219616,1,0,0,0
3,Centro-Oeste,50.0,MS,500070.0,ANASTACIO,50001.0,CAMPO GRANDE,25135.0,4288.840263,111.398448,12747.165307,366.023473,90131.0,45.0,PSDB,Partido da Social Democracia Brasileira,5976.0,4.1,DIREITA_CONSERVADORA,254.625025,1,0,0,0
4,Centro-Oeste,50.0,MS,500080.0,ANAURILANDIA,50003.0,DOURADOS,9035.0,973.990039,22.136137,12484.781406,177.089098,90158.0,45.0,PSDB,Partido da Social Democracia Brasileira,2423.0,4.1,DIREITA_CONSERVADORA,154.952961,1,0,0,0

In [ ]:
bins = pd.IntervalIndex.from_tuples([(0, 25000), (25000, 80000), (80000, 300000), (300000, 1000000), (1000000, 20000000)])
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_30['Tamnho_Mun'] = pd.cut(FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_30['populacaoTCU2019'], bins)
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_30.head()

,regiao,coduf,SG_UF,codmun,NM_MUNICIPIO,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019,casos_Acum_PER_2020_12_31,obitos_Acum_PER_2020_12_31,casos_Acum_PER_2022-05-20,obitos_Acum_PER_2022-05-20,CD_MUNICIPIO,NR_PARTIDO_2020,SG_PARTIDO_2020,NM_PARTIDO_2020,QT_VOTOS_NOMINAIS_2020,PLB_2013_2020,ESPECTRO_2020,obitos_Acum_PER_Aumento_2020,ESPECTRO_2020B_DIREITA_CONSERVADORA,ESPECTRO_2020B_DIREITA_PROGRESSISTA,ESPECTRO_2020B_ESQUERDA_CONSERVADORA,ESPECTRO_2020B_ESQUERDA_PROGRESSISTA,Tamnho_Mun
0,Centro-Oeste,50.0,MS,500020.0,AGUA CLARA,50004.0,TRES LAGOAS,15522.0,3691.534596,25.769875,29339.002706,444.530344,90034.0,55.0,PSD,Partido Social Democrático,3605.0,6.0,DIREITA_CONSERVADORA,418.760469,1,0,0,0,"(0, 25000]"
1,Centro-Oeste,50.0,MS,500025.0,ALCINOPOLIS,50001.0,CAMPO GRANDE,5343.0,935.803856,37.432154,15197.454614,262.025080,55018.0,25.0,DEM,Democratas,2233.0,6.4,DIREITA_CONSERVADORA,224.592925,1,0,0,0,"(0, 25000]"
2,Centro-Oeste,50.0,MS,500060.0,AMAMBAI,50003.0,DOURADOS,39396.0,2969.844654,45.689918,14831.454970,258.909534,90115.0,45.0,PSDB,Partido da Social Democracia Brasileira,11157.0,4.1,DIREITA_CONSERVADORA,213.219616,1,0,0,0,"(25000, 80000]"
3,Centro-Oeste,50.0,MS,500070.0,ANASTACIO,50001.0,CAMPO GRANDE,25135.0,4288.840263,111.398448,12747.165307,366.023473,90131.0,45.0,PSDB,Partido da Social Democracia Brasileira,5976.0,4.1,DIREITA_CONSERVADORA,254.625025,1,0,0,0,"(25000, 80000]"
4,Centro-Oeste,50.0,MS,500080.0,ANAURILANDIA,50003.0,DOURADOS,9035.0,973.990039,22.136137,12484.781406,177.089098,90158.0,45.0,PSDB,Partido da Social Democracia Brasileira,2423.0,4.1,DIREITA_CONSERVADORA,154.952961,1,0,0,0,"(0, 25000]"

In [ ]:
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40 = FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_30.copy()
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40.drop(['CD_MUNICIPIO', 'QT_VOTOS_NOMINAIS_2020', 'coduf', 'codmun', 'casos_Acum_PER_2020_12_31', 'casos_Acum_PER_2022-05-20'], axis=1, inplace=True)
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40.head()

,regiao,SG_UF,NM_MUNICIPIO,codRegiaoSaude,nomeRegiaoSaude,populacaoTCU2019,obitos_Acum_PER_2020_12_31,obitos_Acum_PER_2022-05-20,NR_PARTIDO_2020,SG_PARTIDO_2020,NM_PARTIDO_2020,PLB_2013_2020,ESPECTRO_2020,obitos_Acum_PER_Aumento_2020,ESPECTRO_2020B_DIREITA_CONSERVADORA,ESPECTRO_2020B_DIREITA_PROGRESSISTA,ESPECTRO_2020B_ESQUERDA_CONSERVADORA,ESPECTRO_2020B_ESQUERDA_PROGRESSISTA,Tamnho_Mun
0,Centro-Oeste,MS,AGUA CLARA,50004.0,TRES LAGOAS,15522.0,25.769875,444.530344,55.0,PSD,Partido Social Democrático,6.0,DIREITA_CONSERVADORA,418.760469,1,0,0,0,"(0, 25000]"
1,Centro-Oeste,MS,ALCINOPOLIS,50001.0,CAMPO GRANDE,5343.0,37.432154,262.025080,25.0,DEM,Democratas,6.4,DIREITA_CONSERVADORA,224.592925,1,0,0,0,"(0, 25000]"
2,Centro-Oeste,MS,AMAMBAI,50003.0,DOURADOS,39396.0,45.689918,258.909534,45.0,PSDB,Partido da Social Democracia Brasileira,4.1,DIREITA_CONSERVADORA,213.219616,1,0,0,0,"(25000, 80000]"
3,Centro-Oeste,MS,ANASTACIO,50001.0,CAMPO GRANDE,25135.0,111.398448,366.023473,45.0,PSDB,Partido da Social Democracia Brasileira,4.1,DIREITA_CONSERVADORA,254.625025,1,0,0,0,"(25000, 80000]"
4,Centro-Oeste,MS,ANAURILANDIA,50003.0,DOURADOS,9035.0,22.136137,177.089098,45.0,PSDB,Partido da Social Democracia Brasileira,4.1,DIREITA_CONSERVADORA,154.952961,1,0,0,0,"(0, 25000]"

In [ ]:
colunas = ['regiao', 'SG_UF', 'NM_MUNICIPIO', 'populacaoTCU2019', 'Tamnho_Mun', 
           'NR_PARTIDO_2020', 'SG_PARTIDO_2020', 
           'NM_PARTIDO_2020', 'PLB_2013_2020', 'ESPECTRO_2020', 
           'ESPECTRO_2020B_DIREITA_CONSERVADORA', 'ESPECTRO_2020B_DIREITA_PROGRESSISTA', 
           'ESPECTRO_2020B_ESQUERDA_CONSERVADORA', 'ESPECTRO_2020B_ESQUERDA_PROGRESSISTA', 
           'obitos_Acum_PER_2020_12_31', 'obitos_Acum_PER_2022-05-20', 
           'obitos_Acum_PER_Aumento_2020', 'codRegiaoSaude', 'nomeRegiaoSaude']
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40 = FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40 [colunas].copy()

FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40.columns = ['regiao', 'SG_UF', 'NM_MUNICIPIO', 'populacaoTCU2019', 'Tamnho_Mun', 
                                                             'NR_PARTIDO_2020', 'SG_PARTIDO_2020', 
                                                             'NM_PARTIDO_2020', 'PLB_2013_2020', 'ESPECTRO_2020', 
                                                             'ESPECTRO_2020_DIREITA_CONSERVADORA', 'ESPECTRO_2020_DIREITA_PROGRESSISTA', 
                                                             'ESPECTRO_2020_ESQUERDA_CONSERVADORA', 'ESPECTRO_2020_ESQUERDA_PROGRESSISTA', 
                                                             'obitos_Acum_PER_2020_12_31', 'obitos_Acum_PER_2022-05-20', 
                                                             'obitos_Acum_PER_Aumento_2020', 'codRegiaoSaude', 'nomeRegiaoSaude']

FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40.head()

,regiao,SG_UF,NM_MUNICIPIO,populacaoTCU2019,Tamnho_Mun,NR_PARTIDO_2020,SG_PARTIDO_2020,NM_PARTIDO_2020,PLB_2013_2020,ESPECTRO_2020,ESPECTRO_2020_DIREITA_CONSERVADORA,ESPECTRO_2020_DIREITA_PROGRESSISTA,ESPECTRO_2020_ESQUERDA_CONSERVADORA,ESPECTRO_2020_ESQUERDA_PROGRESSISTA,obitos_Acum_PER_2020_12_31,obitos_Acum_PER_2022-05-20,obitos_Acum_PER_Aumento_2020,codRegiaoSaude,nomeRegiaoSaude
0,Centro-Oeste,MS,AGUA CLARA,15522.0,"(0, 25000]",55.0,PSD,Partido Social Democrático,6.0,DIREITA_CONSERVADORA,1,0,0,0,25.769875,444.530344,418.760469,50004.0,TRES LAGOAS
1,Centro-Oeste,MS,ALCINOPOLIS,5343.0,"(0, 25000]",25.0,DEM,Democratas,6.4,DIREITA_CONSERVADORA,1,0,0,0,37.432154,262.025080,224.592925,50001.0,CAMPO GRANDE
2,Centro-Oeste,MS,AMAMBAI,39396.0,"(25000, 80000]",45.0,PSDB,Partido da Social Democracia Brasileira,4.1,DIREITA_CONSERVADORA,1,0,0,0,45.689918,258.909534,213.219616,50003.0,DOURADOS
3,Centro-Oeste,MS,ANASTACIO,25135.0,"(25000, 80000]",45.0,PSDB,Partido da Social Democracia Brasileira,4.1,DIREITA_CONSERVADORA,1,0,0,0,111.398448,366.023473,254.625025,50001.0,CAMPO GRANDE
4,Centro-Oeste,MS,ANAURILANDIA,9035.0,"(0, 25000]",45.0,PSDB,Partido da Social Democracia Brasileira,4.1,DIREITA_CONSERVADORA,1,0,0,0,22.136137,177.089098,154.952961,50003.0,DOURADOS

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/'
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40.to_excel(folder_path+'FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40.xlsx', sheet_name='ELEICAO', index=False)

# **Fusão Dados COVID com Dados Eleitorais - TSE com IBGE**

In [ ]:
FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40[FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40['NM_MUNICIPIO']=='PALMAREZ PAULISTA']

Empty DataFrame
Columns: [regiao, SG_UF, NM_MUNICIPIO, populacaoTCU2019, Tamnho_Mun, NR_PARTIDO_2020, SG_PARTIDO_2020, NM_PARTIDO_2020, PLB_2013_2020, ESPECTRO_2020, ESPECTRO_2020_DIREITA_CONSERVADORA, ESPECTRO_2020_DIREITA_PROGRESSISTA, ESPECTRO_2020_ESQUERDA_CONSERVADORA, ESPECTRO_2020_ESQUERDA_PROGRESSISTA, obitos_Acum_PER_2020_12_31, obitos_Acum_PER_2022-05-20, obitos_Acum_PER_Aumento_2020, codRegiaoSaude, nomeRegiaoSaude]
Index: []

In [ ]:
FUSÃO_COVID_TSE_IBGE = pd.merge(FUSÃO_DADOS_ELEITORAIS_COVID_PREFEITOS_ELEITOS_40, Tabelao_IBGE,
                                how='left', on=['NM_MUNICIPIO', 'SG_UF'])

FUSÃO_COVID_TSE_IBGE.head()

,regiao,SG_UF,NM_MUNICIPIO,populacaoTCU2019,Tamnho_Mun,NR_PARTIDO_2020,SG_PARTIDO_2020,NM_PARTIDO_2020,PLB_2013_2020,ESPECTRO_2020,ESPECTRO_2020_DIREITA_CONSERVADORA,ESPECTRO_2020_DIREITA_PROGRESSISTA,ESPECTRO_2020_ESQUERDA_CONSERVADORA,ESPECTRO_2020_ESQUERDA_PROGRESSISTA,obitos_Acum_PER_2020_12_31,obitos_Acum_PER_2022-05-20,obitos_Acum_PER_Aumento_2020,codRegiaoSaude,nomeRegiaoSaude,Saneamento_Edificios_Abastecidos_Agua_2017,Saneamento_Edificios_Esgotados_2017,Pobreza_%_2003,Gini_2003,PIB_per_capita_2019,Rendimento_mensal_per_capita_Até_meio_SM_%_2010,Saneamento_Esgotamento_adequado_%_2010,Urbanização_%_vias_públicas_2010,Mortalidade_infantil_PER_MIL_2012_2014,Educacao_Anos_finais_Fundamental_2015,Educacao_Anos_iniciais_Fundamental_2015,Rendimento_médio_mensal_SM_2015,Internações_Diarreia_PER_MIL_2016,População_ocupada_%_2019,Educação_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_%_2010,Educação_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_%_2010,Educação_10_anos_ou_mais_Médio_completo_e_superior_incompleto_%_2010,Educação_10_anos_ou_mais_Superior_%_completo_2010,Educação_10_anos_ou_mais_Ocupada_%_2010,Educação_10_anos_ou_mais_Não_ocupada_%_2010,IDH_2010,Despesas_orçamentárias_empenhadas_2017,Indice_Educacao_Médio_Pública_2019,Indice_Educacao_Fundamental_Anos_finais_Pública_2019,Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019,Notificações_Dengue_2012,Idade_0_a_4_2010,Idade_5_a_9_2010,Idade_10_a_14_2010,Idade_15_a_19_2010,Idade_20_a_24_2010,Idade_25_a_29_2010,Idade_30_a_39_2010,Idade_40_a_49_2010,Idade_50_a_59_2010,Idade_60_a_69_2010,Idade_70_a_mais_2010,Cor_Amarela_%_2010,Cor_Branca_%_2010,Cor_Indígena_%_2010,Cor_Parda_%_2010,Cor_Preta_%_2010,Sem_Declaração_de_Cor_%_2010,Saneamento_Adequado_%_2010,Saneamento_Inadequado_%_2010,Saneamento_Semi-adequado_%_2010,Taxa_analfabetismo_população_15_anos_ou_mais_%_2010
0,Centro-Oeste,MS,AGUA CLARA,15522.0,"(0, 25000]",55.0,PSD,Partido Social Democrático,6.0,DIREITA_CONSERVADORA,1,0,0,0,25.769875,444.530344,418.760469,50004.0,TRES LAGOAS,4814.0,0.0,33.06,0.41,72697.25,33.3,3.8,6.4,12.7,5.2,6.4,2.5,0.3,29.0,65.724472,16.221034,13.131313,4.388422,60.402343,39.606145,0.670,6.503935e+07,0.0,5.0,5.9,3.0,1355.0,1426.0,1299.0,1422.0,1414.0,2467.0,1823.0,1143.0,1288.0,504.0,283.0,1.564027,40.748499,0.153610,48.931713,8.602151,0.0,3.3,25.5,71.1,9.0
1,Centro-Oeste,MS,ALCINOPOLIS,5343.0,"(0, 25000]",25.0,DEM,Democratas,6.4,DIREITA_CONSERVADORA,1,0,0,0,37.432154,262.025080,224.592925,50001.0,CAMPO GRANDE,1640.0,0.0,40.28,0.40,31408.71,32.2,0.4,3.2,0.0,0.0,5.3,2.5,0.0,11.5,61.146990,16.791527,14.259881,7.698269,61.973650,38.026350,0.711,3.050315e+07,0.0,4.2,5.3,2.0,339.0,397.0,418.0,425.0,411.0,768.0,657.0,419.0,359.0,233.0,143.0,0.482774,49.155146,0.043889,44.612684,5.705508,0.0,0.4,32.3,67.3,11.0
2,Centro-Oeste,MS,AMAMBAI,39396.0,"(25000, 80000]",45.0,PSDB,Partido da Social Democracia Brasileira,4.1,DIREITA_CONSERVADORA,1,0,0,0,45.689918,258.909534,213.219616,50003.0,DOURADOS,9025.0,3027.0,35.84,0.45,24687.68,37.8,23.7,13.1,28.0,4.1,5.7,2.0,6.3,13.9,60.371617,15.802664,17.120149,6.412001,53.891594,46.108406,0.673,1.175815e+08,4.1,5.2,6.0,7.0,3290.0,3544.0,3454.0,2951.0,2939.0,5140.0,3822.0,2721.0,3508.0,1820.0,1541.0,0.377863,50.735380,20.930706,25.752819,2.203232,0.0,22.5,16.1,61.4,11.1
3,Centro-Oeste,MS,ANASTACIO,25135.0,"(25000, 80000]",45.0,PSDB,Partido da Social Democracia Brasileira,4.1,DIREITA_CONSERVADORA,1,0,0,0,111.398448,366.023473,254.625025,50001.0,CAMPO GRANDE,7331.0,1164.0,41.22,0.44,19920.79,37.6,45.3,7.8,13.2,3.8,4.6,1.8,0.2,11.4,62.281098,16.092127,15.911486,5.554719,54.282704,45.717296,0.663,4.473767e+07,3.4,4.3,4.7,45.0,1822.0,2223.0,2237.0,1903.0,1939.0,3500.0,3037.0,2325.0,2084.0,1529.0,1236.0,1.098300,41.323010,6.097458,47.517253,3.963979,0.0,39.9,12.3,47.8,11.5
4,Centro-Oeste,MS,ANAURILANDIA,9035.0,"(0, 25000]",45.0,PSDB,Partido da Social Democracia Brasileira,4.1,DIREITA_CONSERVADORA,1,0,0,0,22.136137,177.089098,154.952961,50003.0,DOURADOS,2356.0,0.0,37.91,0.43,28893.11,36.7,1.8,3.8,19.9,3.7,4.6,2.0,4.3,12.5,66.075914,13.326821,15.140943,5.149316,50.362824,49.637176,0.670,2.676084e+07,4.1,3.9,5.7,2.0,610.0,848.0,777.0,628.0,726.0,1305.0,1142.0,801.0,717.0,516.0,423.0,0.930945,40.395946,0.141409,54.100872,4.430827,0.0,1.4,36.9,61.7,12.0

In [ ]:
FUSÃO_COVID_TSE_IBGE['Saneamento_Edificios_Abastecidos_Agua_PER_2017'] = FUSÃO_COVID_TSE_IBGE['Saneamento_Edificios_Abastecidos_Agua_2017'] / FUSÃO_COVID_TSE_IBGE['populacaoTCU2019'] * 100
FUSÃO_COVID_TSE_IBGE['Saneamento_Edificios_Esgotados_PER_2017'] = FUSÃO_COVID_TSE_IBGE['Saneamento_Edificios_Esgotados_2017'] / FUSÃO_COVID_TSE_IBGE['populacaoTCU2019'] * 100
FUSÃO_COVID_TSE_IBGE['Despesas_orçamentárias_empenhadas_PER_2017'] = FUSÃO_COVID_TSE_IBGE['Despesas_orçamentárias_empenhadas_2017'] / FUSÃO_COVID_TSE_IBGE['populacaoTCU2019']

FUSÃO_COVID_TSE_IBGE['Notificações_Dengue_PER_MIL_2012'] = FUSÃO_COVID_TSE_IBGE['Notificações_Dengue_2012'] / FUSÃO_COVID_TSE_IBGE['populacaoTCU2019'] * 1000

FUSÃO_COVID_TSE_IBGE ['Total_pop'] = FUSÃO_COVID_TSE_IBGE['Idade_0_a_4_2010'] + FUSÃO_COVID_TSE_IBGE['Idade_5_a_9_2010'] + FUSÃO_COVID_TSE_IBGE['Idade_10_a_14_2010'] + FUSÃO_COVID_TSE_IBGE['Idade_15_a_19_2010'] + FUSÃO_COVID_TSE_IBGE['Idade_20_a_24_2010'] + FUSÃO_COVID_TSE_IBGE['Idade_25_a_29_2010'] +FUSÃO_COVID_TSE_IBGE['Idade_30_a_39_2010'] + FUSÃO_COVID_TSE_IBGE['Idade_40_a_49_2010'] + FUSÃO_COVID_TSE_IBGE['Idade_50_a_59_2010'] + FUSÃO_COVID_TSE_IBGE['Idade_60_a_69_2010'] + FUSÃO_COVID_TSE_IBGE['Idade_70_a_mais_2010']

FUSÃO_COVID_TSE_IBGE['Idade_0_a_4_%_2010'] = FUSÃO_COVID_TSE_IBGE['Idade_0_a_4_2010'] / FUSÃO_COVID_TSE_IBGE['Total_pop'] * 100
FUSÃO_COVID_TSE_IBGE['Idade_5_a_9_%_2010'] = FUSÃO_COVID_TSE_IBGE['Idade_5_a_9_2010'] / FUSÃO_COVID_TSE_IBGE['Total_pop'] * 100
FUSÃO_COVID_TSE_IBGE['Idade_10_a_14_%_2010'] = FUSÃO_COVID_TSE_IBGE['Idade_10_a_14_2010'] / FUSÃO_COVID_TSE_IBGE['Total_pop'] * 100
FUSÃO_COVID_TSE_IBGE['Idade_15_a_19_%_2010'] = FUSÃO_COVID_TSE_IBGE['Idade_15_a_19_2010'] / FUSÃO_COVID_TSE_IBGE['Total_pop'] * 100
FUSÃO_COVID_TSE_IBGE['Idade_20_a_24_%_2010'] = FUSÃO_COVID_TSE_IBGE['Idade_20_a_24_2010'] / FUSÃO_COVID_TSE_IBGE['Total_pop'] * 100
FUSÃO_COVID_TSE_IBGE['Idade_25_a_29_%_2010'] = FUSÃO_COVID_TSE_IBGE['Idade_25_a_29_2010'] / FUSÃO_COVID_TSE_IBGE['Total_pop'] * 100
FUSÃO_COVID_TSE_IBGE['Idade_30_a_39_%_2010'] = FUSÃO_COVID_TSE_IBGE['Idade_30_a_39_2010'] / FUSÃO_COVID_TSE_IBGE['Total_pop'] * 100
FUSÃO_COVID_TSE_IBGE['Idade_40_a_49_%_2010'] = FUSÃO_COVID_TSE_IBGE['Idade_40_a_49_2010'] / FUSÃO_COVID_TSE_IBGE['Total_pop'] * 100
FUSÃO_COVID_TSE_IBGE['Idade_50_a_59_%_2010'] = FUSÃO_COVID_TSE_IBGE['Idade_50_a_59_2010'] / FUSÃO_COVID_TSE_IBGE['Total_pop'] * 100
FUSÃO_COVID_TSE_IBGE['Idade_60_a_69_%_2010'] = FUSÃO_COVID_TSE_IBGE['Idade_60_a_69_2010'] / FUSÃO_COVID_TSE_IBGE['Total_pop'] * 100
FUSÃO_COVID_TSE_IBGE['Idade_70_a_mais_%_2010'] = FUSÃO_COVID_TSE_IBGE['Idade_70_a_mais_2010'] / FUSÃO_COVID_TSE_IBGE['Total_pop'] * 100

In [ ]:
colunas_apagar = ['NM_PARTIDO_2020', 'obitos_Acum_PER_2020_12_31', 
                  'obitos_Acum_PER_2022-05-20', 'Saneamento_Edificios_Abastecidos_Agua_2017',
                  'Saneamento_Edificios_Esgotados_2017', 'Despesas_orçamentárias_empenhadas_2017',
                  'Notificações_Dengue_2012', 'Idade_0_a_4_2010', 'Idade_5_a_9_2010', 
                  'Idade_10_a_14_2010', 'Idade_15_a_19_2010', 'Idade_20_a_24_2010', 
                  'Idade_25_a_29_2010', 'Idade_30_a_39_2010', 'Idade_40_a_49_2010', 
                  'Idade_50_a_59_2010', 'Idade_60_a_69_2010', 'Idade_70_a_mais_2010',
                  'Total_pop']

FUSÃO_COVID_TSE_IBGE.drop(colunas_apagar, axis=1, inplace=True)

FUSÃO_COVID_TSE_IBGE_10 = FUSÃO_COVID_TSE_IBGE.copy()

colunas = ['regiao', 'SG_UF', 'NM_MUNICIPIO', 'populacaoTCU2019', 'Tamnho_Mun', 
           'NR_PARTIDO_2020', 'SG_PARTIDO_2020', 'PLB_2013_2020', 
           'ESPECTRO_2020', 'ESPECTRO_2020_DIREITA_CONSERVADORA', 'ESPECTRO_2020_DIREITA_PROGRESSISTA',
           'ESPECTRO_2020_ESQUERDA_CONSERVADORA', 'ESPECTRO_2020_ESQUERDA_PROGRESSISTA',
           'codRegiaoSaude', 'nomeRegiaoSaude', 'Pobreza_%_2003', 
           'Gini_2003', 'PIB_per_capita_2019', 'Rendimento_mensal_per_capita_Até_meio_SM_%_2010',
           'Saneamento_Esgotamento_adequado_%_2010', 'Urbanização_%_vias_públicas_2010',
           'Mortalidade_infantil_PER_MIL_2012_2014', 'Educacao_Anos_finais_Fundamental_2015',
           'Educacao_Anos_iniciais_Fundamental_2015', 'Rendimento_médio_mensal_SM_2015', 
           'Internações_Diarreia_PER_MIL_2016', 'População_ocupada_%_2019',
           'Educação_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_%_2010',
           'Educação_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_%_2010',
           'Educação_10_anos_ou_mais_Médio_completo_e_superior_incompleto_%_2010',
           'Educação_10_anos_ou_mais_Superior_%_completo_2010', 'Educação_10_anos_ou_mais_Ocupada_%_2010',
           'Educação_10_anos_ou_mais_Não_ocupada_%_2010', 'IDH_2010', 'Indice_Educacao_Médio_Pública_2019',
           'Indice_Educacao_Fundamental_Anos_finais_Pública_2019', 'Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019',
           'Cor_Amarela_%_2010', 'Cor_Branca_%_2010', 'Cor_Indígena_%_2010', 'Cor_Parda_%_2010', 
           'Cor_Preta_%_2010', 'Sem_Declaração_de_Cor_%_2010', 'Saneamento_Adequado_%_2010', 
           'Saneamento_Inadequado_%_2010', 'Saneamento_Semi-adequado_%_2010',
           'Taxa_analfabetismo_população_15_anos_ou_mais_%_2010',
           'Saneamento_Edificios_Abastecidos_Agua_PER_2017', 'Saneamento_Edificios_Esgotados_PER_2017',
           'Despesas_orçamentárias_empenhadas_PER_2017', 'Notificações_Dengue_PER_MIL_2012', 'Idade_0_a_4_%_2010',
           'Idade_5_a_9_%_2010', 'Idade_10_a_14_%_2010', 'Idade_15_a_19_%_2010', 'Idade_20_a_24_%_2010', 
           'Idade_25_a_29_%_2010', 'Idade_30_a_39_%_2010', 'Idade_40_a_49_%_2010', 'Idade_50_a_59_%_2010', 
           'Idade_60_a_69_%_2010', 'Idade_70_a_mais_%_2010', 'obitos_Acum_PER_Aumento_2020']

FUSÃO_COVID_TSE_IBGE_10 = FUSÃO_COVID_TSE_IBGE_10 [colunas].copy()
FUSÃO_COVID_TSE_IBGE_10.head()

,regiao,SG_UF,NM_MUNICIPIO,populacaoTCU2019,Tamnho_Mun,NR_PARTIDO_2020,SG_PARTIDO_2020,PLB_2013_2020,ESPECTRO_2020,ESPECTRO_2020_DIREITA_CONSERVADORA,ESPECTRO_2020_DIREITA_PROGRESSISTA,ESPECTRO_2020_ESQUERDA_CONSERVADORA,ESPECTRO_2020_ESQUERDA_PROGRESSISTA,codRegiaoSaude,nomeRegiaoSaude,Pobreza_%_2003,Gini_2003,PIB_per_capita_2019,Rendimento_mensal_per_capita_Até_meio_SM_%_2010,Saneamento_Esgotamento_adequado_%_2010,Urbanização_%_vias_públicas_2010,Mortalidade_infantil_PER_MIL_2012_2014,Educacao_Anos_finais_Fundamental_2015,Educacao_Anos_iniciais_Fundamental_2015,Rendimento_médio_mensal_SM_2015,Internações_Diarreia_PER_MIL_2016,População_ocupada_%_2019,Educação_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_%_2010,Educação_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_%_2010,Educação_10_anos_ou_mais_Médio_completo_e_superior_incompleto_%_2010,Educação_10_anos_ou_mais_Superior_%_completo_2010,Educação_10_anos_ou_mais_Ocupada_%_2010,Educação_10_anos_ou_mais_Não_ocupada_%_2010,IDH_2010,Indice_Educacao_Médio_Pública_2019,Indice_Educacao_Fundamental_Anos_finais_Pública_2019,Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019,Cor_Amarela_%_2010,Cor_Branca_%_2010,Cor_Indígena_%_2010,Cor_Parda_%_2010,Cor_Preta_%_2010,Sem_Declaração_de_Cor_%_2010,Saneamento_Adequado_%_2010,Saneamento_Inadequado_%_2010,Saneamento_Semi-adequado_%_2010,Taxa_analfabetismo_população_15_anos_ou_mais_%_2010,Saneamento_Edificios_Abastecidos_Agua_PER_2017,Saneamento_Edificios_Esgotados_PER_2017,Despesas_orçamentárias_empenhadas_PER_2017,Notificações_Dengue_PER_MIL_2012,Idade_0_a_4_%_2010,Idade_5_a_9_%_2010,Idade_10_a_14_%_2010,Idade_15_a_19_%_2010,Idade_20_a_24_%_2010,Idade_25_a_29_%_2010,Idade_30_a_39_%_2010,Idade_40_a_49_%_2010,Idade_50_a_59_%_2010,Idade_60_a_69_%_2010,Idade_70_a_mais_%_2010,obitos_Acum_PER_Aumento_2020
0,Centro-Oeste,MS,AGUA CLARA,15522.0,"(0, 25000]",55.0,PSD,6.0,DIREITA_CONSERVADORA,1,0,0,0,50004.0,TRES LAGOAS,33.06,0.41,72697.25,33.3,3.8,6.4,12.7,5.2,6.4,2.5,0.3,29.0,65.724472,16.221034,13.131313,4.388422,60.402343,39.606145,0.670,0.0,5.0,5.9,1.564027,40.748499,0.153610,48.931713,8.602151,0.0,3.3,25.5,71.1,9.0,31.014045,0.000000,4190.139490,0.193274,9.394065,9.886301,9.005824,9.858569,9.803106,17.103439,12.638658,7.924293,8.929562,3.494176,1.962008,418.760469
1,Centro-Oeste,MS,ALCINOPOLIS,5343.0,"(0, 25000]",25.0,DEM,6.4,DIREITA_CONSERVADORA,1,0,0,0,50001.0,CAMPO GRANDE,40.28,0.40,31408.71,32.2,0.4,3.2,0.0,0.0,5.3,2.5,0.0,11.5,61.146990,16.791527,14.259881,7.698269,61.973650,38.026350,0.711,0.0,4.2,5.3,0.482774,49.155146,0.043889,44.612684,5.705508,0.0,0.4,32.3,67.3,11.0,30.694366,0.000000,5708.992452,0.374322,7.419567,8.688991,9.148610,9.301817,8.995404,16.808930,14.379514,9.170497,7.857299,5.099584,3.129788,224.592925
2,Centro-Oeste,MS,AMAMBAI,39396.0,"(25000, 80000]",45.0,PSDB,4.1,DIREITA_CONSERVADORA,1,0,0,0,50003.0,DOURADOS,35.84,0.45,24687.68,37.8,23.7,13.1,28.0,4.1,5.7,2.0,6.3,13.9,60.371617,15.802664,17.120149,6.412001,53.891594,46.108406,0.673,4.1,5.2,6.0,0.377863,50.735380,20.930706,25.752819,2.203232,0.0,22.5,16.1,61.4,11.1,22.908417,7.683521,2984.604987,0.177683,9.473078,10.204434,9.945292,8.496977,8.462424,14.799885,11.004895,7.834725,10.100777,5.240426,4.437086,213.219616
3,Centro-Oeste,MS,ANASTACIO,25135.0,"(25000, 80000]",45.0,PSDB,4.1,DIREITA_CONSERVADORA,1,0,0,0,50001.0,CAMPO GRANDE,41.22,0.44,19920.79,37.6,45.3,7.8,13.2,3.8,4.6,1.8,0.2,11.4,62.281098,16.092127,15.911486,5.554719,54.282704,45.717296,0.663,3.4,4.3,4.7,1.098300,41.323010,6.097458,47.517253,3.963979,0.0,39.9,12.3,47.8,11.5,29.166501,4.630993,1779.895223,1.790332,7.644221,9.326621,9.385358,7.984057,8.135095,14.684288,12.741766,9.754563,8.743445,6.414936,5.185651,254.625025
4,Centro-Oeste,MS,ANAURILANDIA,9035.0,"(0, 25000]",45.0,PSDB,4.1,DIREITA_CONSERVADORA,1,0,0,0,50003.0,DOURADOS,37.91,0.43,28893.11,36.7,1.8,3.8,19.9,3.7,4.6,2.0,4.3,12.5,66.075914,13.326821,15.140943,5.149316,50.362824,49.637176,0.670,4.1,3.9,5.7,0.930945,40.395946,0.141409,54.100872,4.430827,0.0,1.4,36.9,61.7,12.0,26.076370,0.000000,2961.908437,0.221361,7.182385,9.984693,9.148711,7.394325,8.548216,15.365595,13.446368,9.431296,8.442247,6.075592,4.980572,154.952961

In [ ]:
''' 
 'QT_CONTR_SUS', 'QT_EXIST_SUS', 
                  'QT_SUS', 'QT_CONTR_REGIAO_SUS', 'QT_EXIST_REGIAO_SUS', 
                  'QT_SUS_REGIAO', 

'populacaoTCU2019_REGIAO', 'QT_CONTR_SUS_PER*10000',
           'QT_EXIST_SUS_PER*10000', 'QT_SUS_PER*10000', 'QT_CONTR_REGIAO_SUS_PER*10000', 
           'QT_EXIST_REGIAO_SUS_PER*10000', 'QT_SUS_REGIAO_PER*10000',           
'''

" \n 'QT_CONTR_SUS', 'QT_EXIST_SUS', \n                  'QT_SUS', 'QT_CONTR_REGIAO_SUS', 'QT_EXIST_REGIAO_SUS', \n                  'QT_SUS_REGIAO', \n\n'populacaoTCU2019_REGIAO', 'QT_CONTR_SUS_PER*10000',\n           'QT_EXIST_SUS_PER*10000', 'QT_SUS_PER*10000', 'QT_CONTR_REGIAO_SUS_PER*10000', \n           'QT_EXIST_REGIAO_SUS_PER*10000', 'QT_SUS_REGIAO_PER*10000',           \n"

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/'
FUSÃO_COVID_TSE_IBGE_10.to_excel(folder_path + 'FUSÃO_COVID_TSE_IBGE_10.xlsx', sheet_name='FUSÃO_COVID_TSE_IBGE_10', index=False)

# **Fusão Dados COVID com Dados Eleitorais - TSE com IBGE com Leitos de SUS**

In [ ]:
Tab_Leitos_40[Tab_Leitos_40['NM_MUNICIPIO']=="GUAJARA-MIRIM"]

Empty DataFrame
Columns: [NM_MUNICIPIO, SG_UF, CO_MUNICIPIO, QT_CONTR, QT_EXIST, QT_SUS]
Index: []

In [ ]:
FUSÃO_COVID_TSE_IBGE_SUS = FUSÃO_COVID_TSE_IBGE_10.merge(Tab_Leitos_40, how='left', 
                                                         on=['NM_MUNICIPIO', 'SG_UF'])
FUSÃO_COVID_TSE_IBGE_SUS [['QT_CONTR', 'QT_EXIST', 'QT_SUS']] = FUSÃO_COVID_TSE_IBGE_SUS [['QT_CONTR', 'QT_EXIST', 'QT_SUS']].fillna(0).copy()
FUSÃO_COVID_TSE_IBGE_SUS.drop(['CO_MUNICIPIO'], axis=1, inplace=True)

FUSÃO_COVID_TSE_IBGE_SUS.head()

,regiao,SG_UF,NM_MUNICIPIO,populacaoTCU2019,Tamnho_Mun,NR_PARTIDO_2020,SG_PARTIDO_2020,PLB_2013_2020,ESPECTRO_2020,ESPECTRO_2020_DIREITA_CONSERVADORA,ESPECTRO_2020_DIREITA_PROGRESSISTA,ESPECTRO_2020_ESQUERDA_CONSERVADORA,ESPECTRO_2020_ESQUERDA_PROGRESSISTA,codRegiaoSaude,nomeRegiaoSaude,Pobreza_%_2003,Gini_2003,PIB_per_capita_2019,Rendimento_mensal_per_capita_Até_meio_SM_%_2010,Saneamento_Esgotamento_adequado_%_2010,Urbanização_%_vias_públicas_2010,Mortalidade_infantil_PER_MIL_2012_2014,Educacao_Anos_finais_Fundamental_2015,Educacao_Anos_iniciais_Fundamental_2015,Rendimento_médio_mensal_SM_2015,Internações_Diarreia_PER_MIL_2016,População_ocupada_%_2019,Educação_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_%_2010,Educação_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_%_2010,Educação_10_anos_ou_mais_Médio_completo_e_superior_incompleto_%_2010,Educação_10_anos_ou_mais_Superior_%_completo_2010,Educação_10_anos_ou_mais_Ocupada_%_2010,Educação_10_anos_ou_mais_Não_ocupada_%_2010,IDH_2010,Indice_Educacao_Médio_Pública_2019,Indice_Educacao_Fundamental_Anos_finais_Pública_2019,Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019,Cor_Amarela_%_2010,Cor_Branca_%_2010,Cor_Indígena_%_2010,Cor_Parda_%_2010,Cor_Preta_%_2010,Sem_Declaração_de_Cor_%_2010,Saneamento_Adequado_%_2010,Saneamento_Inadequado_%_2010,Saneamento_Semi-adequado_%_2010,Taxa_analfabetismo_população_15_anos_ou_mais_%_2010,Saneamento_Edificios_Abastecidos_Agua_PER_2017,Saneamento_Edificios_Esgotados_PER_2017,Despesas_orçamentárias_empenhadas_PER_2017,Notificações_Dengue_PER_MIL_2012,Idade_0_a_4_%_2010,Idade_5_a_9_%_2010,Idade_10_a_14_%_2010,Idade_15_a_19_%_2010,Idade_20_a_24_%_2010,Idade_25_a_29_%_2010,Idade_30_a_39_%_2010,Idade_40_a_49_%_2010,Idade_50_a_59_%_2010,Idade_60_a_69_%_2010,Idade_70_a_mais_%_2010,obitos_Acum_PER_Aumento_2020,QT_CONTR,QT_EXIST,QT_SUS
0,Centro-Oeste,MS,AGUA CLARA,15522.0,"(0, 25000]",55.0,PSD,6.0,DIREITA_CONSERVADORA,1,0,0,0,50004.0,TRES LAGOAS,33.06,0.41,72697.25,33.3,3.8,6.4,12.7,5.2,6.4,2.5,0.3,29.0,65.724472,16.221034,13.131313,4.388422,60.402343,39.606145,0.670,0.0,5.0,5.9,1.564027,40.748499,0.153610,48.931713,8.602151,0.0,3.3,25.5,71.1,9.0,31.014045,0.000000,4190.139490,0.193274,9.394065,9.886301,9.005824,9.858569,9.803106,17.103439,12.638658,7.924293,8.929562,3.494176,1.962008,418.760469,0.0,21.0,21.0
1,Centro-Oeste,MS,ALCINOPOLIS,5343.0,"(0, 25000]",25.0,DEM,6.4,DIREITA_CONSERVADORA,1,0,0,0,50001.0,CAMPO GRANDE,40.28,0.40,31408.71,32.2,0.4,3.2,0.0,0.0,5.3,2.5,0.0,11.5,61.146990,16.791527,14.259881,7.698269,61.973650,38.026350,0.711,0.0,4.2,5.3,0.482774,49.155146,0.043889,44.612684,5.705508,0.0,0.4,32.3,67.3,11.0,30.694366,0.000000,5708.992452,0.374322,7.419567,8.688991,9.148610,9.301817,8.995404,16.808930,14.379514,9.170497,7.857299,5.099584,3.129788,224.592925,0.0,0.0,0.0
2,Centro-Oeste,MS,AMAMBAI,39396.0,"(25000, 80000]",45.0,PSDB,4.1,DIREITA_CONSERVADORA,1,0,0,0,50003.0,DOURADOS,35.84,0.45,24687.68,37.8,23.7,13.1,28.0,4.1,5.7,2.0,6.3,13.9,60.371617,15.802664,17.120149,6.412001,53.891594,46.108406,0.673,4.1,5.2,6.0,0.377863,50.735380,20.930706,25.752819,2.203232,0.0,22.5,16.1,61.4,11.1,22.908417,7.683521,2984.604987,0.177683,9.473078,10.204434,9.945292,8.496977,8.462424,14.799885,11.004895,7.834725,10.100777,5.240426,4.437086,213.219616,0.0,101.0,65.0
3,Centro-Oeste,MS,ANASTACIO,25135.0,"(25000, 80000]",45.0,PSDB,4.1,DIREITA_CONSERVADORA,1,0,0,0,50001.0,CAMPO GRANDE,41.22,0.44,19920.79,37.6,45.3,7.8,13.2,3.8,4.6,1.8,0.2,11.4,62.281098,16.092127,15.911486,5.554719,54.282704,45.717296,0.663,3.4,4.3,4.7,1.098300,41.323010,6.097458,47.517253,3.963979,0.0,39.9,12.3,47.8,11.5,29.166501,4.630993,1779.895223,1.790332,7.644221,9.326621,9.385358,7.984057,8.135095,14.684288,12.741766,9.754563,8.743445,6.414936,5.185651,254.625025,0.0,31.0,30.0
4,Centro-Oeste,MS,ANAURILANDIA,9035.0,"(0, 25000]",45.0,PSDB,4.1,DIREITA_CONSERVADORA,1,0,0,0,50003.0,DOURADOS,37.91,0.43,28893.11,36.7,1.8,3.8,19.9,3.7,4.6,2.0,4.3,12.5,66.075914,13.326821,15.140943,5.149316,50.362824,49.637176,0.670,4.1,3.9,5.7,0.930945,40.395946,0.141409,54.100872,4.430827,0.0,1.4,36.9,61.7,12.0,26.076370,0.000000,2961.908437,0.221361,7.182385,9.984693,9.148711,7.394325,8.548216,15.365595,13.446368,9.431296,8.442247,6.075592,4.980572,154.952961,0.0,12.0,8.0

In [ ]:
Calcula_SUS = FUSÃO_COVID_TSE_IBGE_SUS [['codRegiaoSaude', 'populacaoTCU2019', 'QT_CONTR', 'QT_EXIST', 'QT_SUS']].copy()

Calcula_SUS = pd.pivot_table(Calcula_SUS, values=['populacaoTCU2019', 'QT_CONTR', 'QT_EXIST', 'QT_SUS'], index=['codRegiaoSaude'],
                             aggfunc="sum")

Calcula_SUS = Calcula_SUS.reset_index()

Calcula_SUS.columns = ['codRegiaoSaude', 'QT_CONTR_REGIAO', 'QT_EXIST_REGIAO', 'QT_SUS_REGIAO', 'populacaoTCU2019_REGIAO']

Calcula_SUS.head()

,codRegiaoSaude,QT_CONTR_REGIAO,QT_EXIST_REGIAO,QT_SUS_REGIAO,populacaoTCU2019_REGIAO
0,11001.0,0.0,648.0,406.0,274136.0
1,11002.0,0.0,1063.0,833.0,172081.0
2,11003.0,0.0,1358.0,931.0,343113.0
3,11004.0,0.0,4500.0,3349.0,643452.0
4,11005.0,0.0,287.0,258.0,135877.0

In [ ]:
FUSÃO_COVID_TSE_IBGE_SUS.columns

Index(['regiao', 'SG_UF', 'NM_MUNICIPIO', 'populacaoTCU2019', 'Tamnho_Mun',
       'NR_PARTIDO_2020', 'SG_PARTIDO_2020', 'PLB_2013_2020', 'ESPECTRO_2020',
       'ESPECTRO_2020_DIREITA_CONSERVADORA',
       'ESPECTRO_2020_DIREITA_PROGRESSISTA',
       'ESPECTRO_2020_ESQUERDA_CONSERVADORA',
       'ESPECTRO_2020_ESQUERDA_PROGRESSISTA', 'codRegiaoSaude',
       'nomeRegiaoSaude', 'Pobreza_%_2003', 'Gini_2003', 'PIB_per_capita_2019',
       'Rendimento_mensal_per_capita_Até_meio_SM_%_2010',
       'Saneamento_Esgotamento_adequado_%_2010',
       'Urbanização_%_vias_públicas_2010',
       'Mortalidade_infantil_PER_MIL_2012_2014',
       'Educacao_Anos_finais_Fundamental_2015',
       'Educacao_Anos_iniciais_Fundamental_2015',
       'Rendimento_médio_mensal_SM_2015', 'Internações_Diarreia_PER_MIL_2016',
       'População_ocupada_%_2019',
       'Educação_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_%_2010',
       'Educação_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_%_2010',
       'Educação_10_anos_ou_mais_Médio_completo_e_superior_incompleto_%_2010',
       'Educação_10_anos_ou_mais_Superior_%_completo_2010',
       'Educação_10_anos_ou_mais_Ocupada_%_2010',
       'Educação_10_anos_ou_mais_Não_ocupada_%_2010', 'IDH_2010',
       'Indice_Educacao_Médio_Pública_2019',
       'Indice_Educacao_Fundamental_Anos_finais_Pública_2019',
       'Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019',
       'Cor_Amarela_%_2010', 'Cor_Branca_%_2010', 'Cor_Indígena_%_2010',
       'Cor_Parda_%_2010', 'Cor_Preta_%_2010', 'Sem_Declaração_de_Cor_%_2010',
       'Saneamento_Adequado_%_2010', 'Saneamento_Inadequado_%_2010',
       'Saneamento_Semi-adequado_%_2010',
       'Taxa_analfabetismo_população_15_anos_ou_mais_%_2010',
       'Saneamento_Edificios_Abastecidos_Agua_PER_2017',
       'Saneamento_Edificios_Esgotados_PER_2017',
       'Despesas_orçamentárias_empenhadas_PER_2017',
       'Notificações_Dengue_PER_MIL_2012', 'Idade_0_a_4_%_2010',
       'Idade_5_a_9_%_2010', 'Idade_10_a_14_%_2010', 'Idade_15_a_19_%_2010',
       'Idade_20_a_24_%_2010', 'Idade_25_a_29_%_2010', 'Idade_30_a_39_%_2010',
       'Idade_40_a_49_%_2010', 'Idade_50_a_59_%_2010', 'Idade_60_a_69_%_2010',
       'Idade_70_a_mais_%_2010', 'obitos_Acum_PER_Aumento_2020', 'QT_CONTR',
       'QT_EXIST', 'QT_SUS'],
      dtype='object')

In [ ]:
FUSÃO_COVID_TSE_IBGE_SUS_10 = pd.merge(FUSÃO_COVID_TSE_IBGE_SUS, Calcula_SUS,
                                       how='left', on='codRegiaoSaude')

FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_CONTR_SUS_PER*10000'] = FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_CONTR'] / FUSÃO_COVID_TSE_IBGE_SUS_10 ['populacaoTCU2019'] * 10000
FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_EXIST_SUS_PER*10000'] = FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_EXIST'] / FUSÃO_COVID_TSE_IBGE_SUS_10 ['populacaoTCU2019'] * 10000
FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_SUS_PER*10000'] = FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_SUS'] / FUSÃO_COVID_TSE_IBGE_SUS_10 ['populacaoTCU2019'] * 10000

FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_CONTR_REGIAO_SUS_PER*10000'] = FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_CONTR_REGIAO'] / FUSÃO_COVID_TSE_IBGE_SUS_10 ['populacaoTCU2019_REGIAO'] * 10000
FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_EXIST_REGIAO_SUS_PER*10000'] = FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_EXIST_REGIAO'] / FUSÃO_COVID_TSE_IBGE_SUS_10 ['populacaoTCU2019_REGIAO'] * 10000
FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_SUS_REGIAO_PER*10000'] = FUSÃO_COVID_TSE_IBGE_SUS_10 ['QT_SUS_REGIAO'] / FUSÃO_COVID_TSE_IBGE_SUS_10 ['populacaoTCU2019_REGIAO'] * 10000

FUSÃO_COVID_TSE_IBGE_SUS_10.rename(columns={'QT_CONTR': 'QT_CONTR_SUS', 'QT_EXIST': 'QT_EXIST_SUS', 'QT_CONTR_REGIAO': 'QT_CONTR_REGIAO_SUS', 'QT_EXIST_REGIAO': 'QT_EXIST_REGIAO_SUS'}, inplace = True)

FUSÃO_COVID_TSE_IBGE_SUS_10.head()

,regiao,SG_UF,NM_MUNICIPIO,populacaoTCU2019,Tamnho_Mun,NR_PARTIDO_2020,SG_PARTIDO_2020,PLB_2013_2020,ESPECTRO_2020,ESPECTRO_2020_DIREITA_CONSERVADORA,ESPECTRO_2020_DIREITA_PROGRESSISTA,ESPECTRO_2020_ESQUERDA_CONSERVADORA,ESPECTRO_2020_ESQUERDA_PROGRESSISTA,codRegiaoSaude,nomeRegiaoSaude,Pobreza_%_2003,Gini_2003,PIB_per_capita_2019,Rendimento_mensal_per_capita_Até_meio_SM_%_2010,Saneamento_Esgotamento_adequado_%_2010,Urbanização_%_vias_públicas_2010,Mortalidade_infantil_PER_MIL_2012_2014,Educacao_Anos_finais_Fundamental_2015,Educacao_Anos_iniciais_Fundamental_2015,Rendimento_médio_mensal_SM_2015,Internações_Diarreia_PER_MIL_2016,População_ocupada_%_2019,Educação_10_anos_ou_mais_Sem_instrução_e_fundamental_incompleto_%_2010,Educação_10_anos_ou_mais_Fundamental_completo_e_médio_incompleto_%_2010,Educação_10_anos_ou_mais_Médio_completo_e_superior_incompleto_%_2010,Educação_10_anos_ou_mais_Superior_%_completo_2010,Educação_10_anos_ou_mais_Ocupada_%_2010,Educação_10_anos_ou_mais_Não_ocupada_%_2010,IDH_2010,Indice_Educacao_Médio_Pública_2019,Indice_Educacao_Fundamental_Anos_finais_Pública_2019,Indice_Educacao_Fundamental_Anos_iniciais_Pública_2019,Cor_Amarela_%_2010,Cor_Branca_%_2010,Cor_Indígena_%_2010,Cor_Parda_%_2010,Cor_Preta_%_2010,Sem_Declaração_de_Cor_%_2010,Saneamento_Adequado_%_2010,Saneamento_Inadequado_%_2010,Saneamento_Semi-adequado_%_2010,Taxa_analfabetismo_população_15_anos_ou_mais_%_2010,Saneamento_Edificios_Abastecidos_Agua_PER_2017,Saneamento_Edificios_Esgotados_PER_2017,Despesas_orçamentárias_empenhadas_PER_2017,Notificações_Dengue_PER_MIL_2012,Idade_0_a_4_%_2010,Idade_5_a_9_%_2010,Idade_10_a_14_%_2010,Idade_15_a_19_%_2010,Idade_20_a_24_%_2010,Idade_25_a_29_%_2010,Idade_30_a_39_%_2010,Idade_40_a_49_%_2010,Idade_50_a_59_%_2010,Idade_60_a_69_%_2010,Idade_70_a_mais_%_2010,obitos_Acum_PER_Aumento_2020,QT_CONTR_SUS,QT_EXIST_SUS,QT_SUS,QT_CONTR_REGIAO_SUS,QT_EXIST_REGIAO_SUS,QT_SUS_REGIAO,populacaoTCU2019_REGIAO,QT_CONTR_SUS_PER*10000,QT_EXIST_SUS_PER*10000,QT_SUS_PER*10000,QT_CONTR_REGIAO_SUS_PER*10000,QT_EXIST_REGIAO_SUS_PER*10000,QT_SUS_REGIAO_PER*10000
0,Centro-Oeste,MS,AGUA CLARA,15522.0,"(0, 25000]",55.0,PSD,6.0,DIREITA_CONSERVADORA,1,0,0,0,50004.0,TRES LAGOAS,33.06,0.41,72697.25,33.3,3.8,6.4,12.7,5.2,6.4,2.5,0.3,29.0,65.724472,16.221034,13.131313,4.388422,60.402343,39.606145,0.670,0.0,5.0,5.9,1.564027,40.748499,0.153610,48.931713,8.602151,0.0,3.3,25.5,71.1,9.0,31.014045,0.000000,4190.139490,0.193274,9.394065,9.886301,9.005824,9.858569,9.803106,17.103439,12.638658,7.924293,8.929562,3.494176,1.962008,418.760469,0.0,21.0,21.0,0.0,888.0,538.0,283628.0,0.0,13.529184,13.529184,0.0,31.308616,18.968508
1,Centro-Oeste,MS,ALCINOPOLIS,5343.0,"(0, 25000]",25.0,DEM,6.4,DIREITA_CONSERVADORA,1,0,0,0,50001.0,CAMPO GRANDE,40.28,0.40,31408.71,32.2,0.4,3.2,0.0,0.0,5.3,2.5,0.0,11.5,61.146990,16.791527,14.259881,7.698269,61.973650,38.026350,0.711,0.0,4.2,5.3,0.482774,49.155146,0.043889,44.612684,5.705508,0.0,0.4,32.3,67.3,11.0,30.694366,0.000000,5708.992452,0.374322,7.419567,8.688991,9.148610,9.301817,8.995404,16.808930,14.379514,9.170497,7.857299,5.099584,3.129788,224.592925,0.0,0.0,0.0,0.0,4606.0,2791.0,1520047.0,0.0,0.000000,0.000000,0.0,30.301695,18.361274
2,Centro-Oeste,MS,AMAMBAI,39396.0,"(25000, 80000]",45.0,PSDB,4.1,DIREITA_CONSERVADORA,1,0,0,0,50003.0,DOURADOS,35.84,0.45,24687.68,37.8,23.7,13.1,28.0,4.1,5.7,2.0,6.3,13.9,60.371617,15.802664,17.120149,6.412001,53.891594,46.108406,0.673,4.1,5.2,6.0,0.377863,50.735380,20.930706,25.752819,2.203232,0.0,22.5,16.1,61.4,11.1,22.908417,7.683521,2984.604987,0.177683,9.473078,10.204434,9.945292,8.496977,8.462424,14.799885,11.004895,7.834725,10.100777,5.240426,4.437086,213.219616,0.0,101.0,65.0,0.0,2206.0,1461.0,840545.0,0.0,25.637121,16.499137,0.0,26.244877,17.381580
3,Centro-Oeste,MS,ANASTACIO,25135.0,"(25000, 80000]",45.0,PSDB,4.1,DIREITA_CONSERVADORA,1,0,0,0,50001.0,CAMPO GRANDE,41.22,0.44,19920.79,37.6,45.3,7.8,13.2,3.8,4.6,1.8,0.2,11.4,62.281098,16.092127,15.911486,5.554719,54.282704,45.717296,0.663,3.4,4.3,4.7,1.098300,41.323010,6.097458,47.517253,3.963979,0.0,39.9,12.3,47.8,11.5,29.166501,4.630993,1779.895223,1.790332,7.644221,9.326621,9.385358,7.984057,8.135095,14.684288,12.741766,9.754563,8.743445,6.414936,5.185651,254.625025,0.0,31.0,30.0,0.0,4606.0,2791.0,1520047.0,0.0,12.333400,11.935548,0.0,30.301695,18.361274
4,Centro-Oeste,MS,ANAURILANDIA,9035.0,"(0, 25000]",45.0,PSDB,4.1,DIREITA_CONSERVADORA,1,0,0,0,50003.0,DOURADOS,37.91,0.43,28893.11,36.7,1.8,3.8,19.9,3.7,4.6,2.0,4.3,12.5,66.075914,13.326821,15.140943,5.149316,50.362824,49.637176,0.670,4.1,3.9,5.7,0.930945,40.395946,0.141409,54.100872,4.430827,0.0,1.4,36.9,61.7,12.0,26.076370,0.000000,2961.908437,0.221361,7.182385,9.984693,9.148711,7.394325,8.548216,15.365595,13.446368,9.431296,8.442247,6.075592,4.980572,154.952961,0.0,12.0,8.0,0.0,2206.0,1461.0,840545.0,0.0,13.281682,8.854455,0.0,26.244877,17.381580

In [ ]:
eliminar = ['QT_CONTR_REGIAO_SUS', 'QT_CONTR_SUS', 'QT_EXIST_REGIAO_SUS', 
            'QT_EXIST_SUS', 'QT_SUS', 'QT_SUS_REGIAO']
FUSÃO_COVID_TSE_IBGE_SUS_10.drop(eliminar, axis=1, inplace=True)

In [ ]:
folder_path = '/content/drive/MyDrive/Pos/'
FUSÃO_COVID_TSE_IBGE_SUS_10.to_excel(folder_path + 'FUSÃO_COVID_TSE_IBGE_SUS_10.xlsx', sheet_name='FUSÃO_COVID_TSE_IBGE_SUS_10', index=False)